Repository COS301-SE-2022/Twitter-Summariser, pull requests merged in 2022-07, with the labels that each got.

#336 🐛 ⚡ 🧑‍💻 Improved API response headers for errors in report
  src/functions/report/handler.ts
  src/functions/resources/APIresponse.ts
Labels: priority:medium, status:ready, type:enhance, role:backend-engineer, scope:backend

#335 🚑 (UI): Fixed text editor logical error
  client/src/components/Home/Home.tsx
  client/src/components/Text/Text.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:bug, type:fix, role:designer

#337 🐛 🧪 Fixing failing tests
  src/functions/__tests__/inte/editblock.handler.int.ts
  src/functions/__tests__/inte/generateReport.handler.int.ts
  src/functions/__tests__/inte/resources.ts
  src/functions/report/handler.ts
  src/functions/tweet/handler.ts
Labels: priority:high, status:ready, type:bug, type:fix, role:backend-engineer, scope:backend, role:tester

#339 🗃️ 🔥 (DB) Update function to get all published reports
  src/model/report/index.ts
  src/services/report.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#341 🔥 🚑 🔧 🚀 (CLOUDFRONT) Update distribution ID
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:team-lead, type:change, type:fix, role:backend-engineer, scope:github-repo, scope:cicd

#343 🧪 (TEST) Update endpoint in integration test
  src/functions/__tests__/inte/editblock.handler.int.ts
Labels: priority:high, status:ready, role:team-lead, type:change, role:backend-engineer, scope:backend, role:tester

#338 ⚡️ (UI): added delete icon
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Text/Text.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#346 🎨 ✅ 🐛(UI): Fixed unit tests and removed unused variables
  client/src/App.tsx
  client/src/components/CLReports/CLReports.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Explore/Explore.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/History/History.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Home/__tests__/Home.test.tsx
  client/src/components/Landing/__tests__/Landing.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Logo/__tests__/Logo.test.tsx
  client/src/components/Navigation/__tests__/Navigation.test.tsx
  client/src/components/PageNotFound/PageNotFound.tsx
  client/src/components/Profile/Profile.tsx
  client/src/components/Reports/__tests__/Reports.test.tsx
  client/src/components/Shared/Shared.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
  client/src/components/Splash/Splash.tsx
  client/src/components/Text/Text.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:fix, role:tester

#347 🎨 (UI): Updated variables to camelCase in all variables and added types to buttons
  client/src/App.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Home/__tests__/Home.test.tsx
  client/src/components/HomeTweet/HomeTweet.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
  client/src/components/Text/Text.tsx
  client/src/components/Tweet/Tweet.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:fix, role:tester

#348 ✨ 🔥 Major changes to linting & CI workflow
  .github/workflows/main.yml
  README.md
  client/.eslintignore
  client/.eslintrc.json
  client/.prettierignore
  client/.prettierrc
  client/package.json
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
  client/src/service-worker.ts
  client/src/serviceWorkerRegistration.ts
  client/yarn.lock
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:cicd

#349 🚑 (CICD): Changes to workflows
  .github/workflows/main.yml
  .github/workflows/serverless-deploy.yml
  client/src/App.tsx
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:cicd

#350 📦 (CICD): Updated prettier script
  .github/workflows/main.yml
  .github/workflows/serverless-deploy.yml
  client/package.json
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#351 Updated script
  client/package.json
Labels: priority:high, status:needs-tests, role:dev-op, type:change, scope:cicd

#352 🎨 (UI): Fixed remaining linting errors
  client/.eslintrc.json
  client/src/components/CLReports/CLReports.tsx
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Explore/Explore.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/History/History.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Home/__tests__/Home.test.tsx
  client/src/components/HomeTweet/HomeTweet.tsx
  client/src/components/Landing/Landing.css
  client/src/components/Landing/Landing.tsx
  client/src/components/Landing/__tests__/Landing.test.tsx
  client/src/components/Login/Login.css
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/Logo/__tests__/Logo.test.tsx
  client/src/components/MobileNavigation/MobileNavigation.tsx
  client/src/components/Navigation/Navigation.css
  client/src/components/Navigation/Navigation.tsx
  client/src/components/PageNotFound/PageNotFound.tsx
  client/src/components/Profile/Profile.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/Reports/__tests__/Reports.test.tsx
  client/src/components/Shared/Shared.tsx
  client/src/components/Signup/Signup.css
  client/src/components/Signup/Signup.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
  client/src/components/Splash/Splash.css
  client/src/components/Splash/Splash.tsx
  client/src/components/Text/Text.tsx
  client/src/components/Tweet/Tweet.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
  client/src/editReport.json
  client/src/index.tsx
  client/src/mock.json
  client/src/reportWebVitals.ts
  client/src/service-worker.ts
  client/src/serviceWorkerRegistration.ts
  client/src/setupTests.ts
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#353 (API&Backend)🔒 ✨ 🧑‍💻 Redefined response headers and returned meaningful errors.
  src/functions/__tests__/inte/editblock.handler.int.ts
  src/functions/creator/handler.ts
  src/functions/resultSet/handler.ts
Labels: priority:high, status:ready, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#354 🔥 🗃️ ✅ (DB/SERV) Remove credential checks from creator service
  src/functions/creator/handler.ts
  src/services/__tests__/creator.service.spec.ts
  src/services/creator.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:change, role:backend-engineer, scope:backend, role:tester

#355 ✨ 🗃️ (DB) Add function to get draft reports
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#356 🩹 Add report block ID to get report object
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:change, role:backend-engineer, scope:backend

#360 ✨ 🚑 🔥 ⚡️ 🎨 (UI): Swapped the endpoints where necessary and Editing re…
  client/.eslintrc.json
  client/src/App.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/History/History.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Text/Text.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:fix, role:designer, user story

#359 ✨(SERV) Added function code for report cloning
  src/functions/creator/handler.ts
  src/functions/report/handler.ts
  src/functions/reportBlock/handler.ts
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#362 💚 🔥 ✨ (CICD): Major changes
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  README.md
  client/package.json
  client/src/App.tsx
  client/yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:dev-op, type:enhance, type:change, type:fix, scope:cicd

#364 🐛 ⚡ (SERV/API) Fixed code for lint backend.
  babel.config.js
  client/package.json
  client/postcss.config.js
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
  client/tailwind.config.js
  client/tsconfig.json
  client/yarn.lock
  docker-compose.yml
  jest.config.js
  package.json
  serverless.ts
  src/__mocks__/aws-sdk.ts
  src/functions/creator/handler.ts
  src/functions/creator/index.ts
  src/functions/report/handler.ts
  src/functions/report/index.ts
  src/functions/reportBlock/handler.ts
  src/functions/reportBlock/index.ts
  src/functions/resources/APIresponse.ts
  src/functions/resources/twitterV2.client.ts
  src/functions/resultSet/handler.ts
  src/functions/resultSet/index.ts
  src/functions/tweet/handler.ts
  src/functions/tweet/index.ts
  src/libs/api-gateway.ts
  src/libs/handler-resolver.ts
  src/libs/lambda.ts
  src/model/creator/creator.model.ts
  src/model/creator/index.ts
  src/model/database.ts
  src/model/report/index.ts
  src/model/report/report.model.ts
  src/model/reportBlock/index.ts
  src/model/reportBlock/reportBlock.model.ts
  src/model/resultSet/index.ts
  src/model/resultSet/resultSet.model.ts
  src/model/textStyles/index.ts
  src/model/textStyles/textStyles.model.ts
  src/model/tweet/index.ts
  src/model/tweet/tweet.model.ts
  src/services/__tests__/creator.service.spec.ts
  src/services/__tests__/report.service.spec.ts
  src/services/__tests__/resultSet.service.spec.ts
  src/services/creator.service.ts
  src/services/index.ts
  src/services/report.service.ts
  src/services/reportBlock.service.ts
  src/services/resultSet.service.ts
  src/services/textStyles.service.ts
  src/services/tweet.service.ts
  tools/scripts/merge-reports.js
  tools/tsconfig.tools.json
  tsconfig.json
  tsconfig.paths.json
Labels: priority:high, status:needs-tests, type:bug, type:fix, role:backend-engineer, scope:backend

#365 🎨 ✨ 💚 (CICD): Enhancements to the build workflow
  .github/workflows/build.yml
  client/package.json
  package.json
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, type:fix, scope:github-repo, scope:cicd

#366 ✨ (CICD): Introduced artifacts in workflows
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/serverless-deploy.yml
  client/src/App.tsx
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, scope:cicd

#367 ✨ 💚 (CICD): Changes to deploy workflow
  .github/workflows/serverless-deploy.yml
  client/src/App.tsx
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, scope:cicd

#368 🚑
  .github/workflows/serverless-deploy.yml
  client/src/App.tsx
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#369 attempt to fix deploy
  .github/workflows/build.yml
  client/src/App.tsx
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#370 🚑
  .github/workflows/build.yml
  .github/workflows/serverless-deploy.yml
  client/src/index.tsx
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#371 🚑 (SERVICE) Fix to generate report
  serverless.ts
  src/functions/report/handler.ts
  src/model/permission/index.ts
  src/model/permission/permissions.model.ts
  src/services/index.ts
  src/services/permission.service.ts
Labels: priority:high, status:ready, type:fix, role:backend-engineer, scope:backend

#372 ⚡️ 🔥 💚 (CICD): Update build and deploy workflows
  .github/workflows/build.yml
  .github/workflows/serverless-deploy.yml
  client/src/App.tsx
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, type:fix, scope:github-repo, scope:cicd

#373 ✨ ✏️ 🗃️ (DB) Add more operations for permission table
  src/services/permission.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, type:change, role:backend-engineer, scope:backend

#374 ✨ 🗃️ (DB) Add function to get shared reports
  src/services/permission.service.ts
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#377 ✨ ⚡ 🔒 🚚 (SERV/API) Added code to share report and moved resources to different service layer and improved clone and get report secuirty
  client/package.json
  client/src/App.tsx
  package.json
  serverless.ts
  src/functions/report/handler.ts
  src/model/permission/index.ts
  src/model/permission/permissions.model.ts
  src/services/permission.service.ts
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, type:enhance, type:change, role:backend-engineer, scope:backend

#378 ⚡ ✨ Added code to add permissions for generated report
  src/functions/report/handler.ts
  src/services/permission.service.ts
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, type:enhance, type:change, role:backend-engineer, scope:backend

#379 ✏️ (DB) Fix typo in table name
  src/services/permission.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:fix, role:backend-engineer, scope:backend

#380 ⚡ ✨ added code and endpoint for getShared report
  serverless.ts
  src/functions/report/handler.ts
  src/functions/report/index.ts
  src/functions/resultSet/handler.ts
  src/functions/resultSet/index.ts
  src/services/permission.service.ts
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, type:enhance, type:fix, role:backend-engineer, scope:backend

#383 🎨 (UI): Made changes to endpoint link format
  client/src/App.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
  client/src/resources/links.json
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:fix, role:designer

#384 🎨 (UI): Updated twitter widget alignment
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#385 🎨 (UI): Updated endpoints to new format
  client/src/components/GenReport/GenReport.tsx
  client/src/components/History/History.tsx
  client/src/components/Text/Text.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#386 ✨ (UI): Added delete Icon to Resultset and Drafts
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/History/History.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#387 ✨ 🎨 (UI): Improved tweet component and updated endpoints
  client/src/components/GenReport/GenReport.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#389 🗃️ 🚑 (DB) Fix to delete result set function
  src/functions/resultSet/handler.ts
  src/services/resultSet.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:fix, role:backend-engineer, scope:backend

#395 💄 ⚡️ (UI): Updated Publish report endpoint and also fixed the add and…
  client/src/components/GenReport/GenReport.tsx
  client/src/components/GetPublishedReport/GetPublishedReport.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Text/Text.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#394 ✨ 🗃️ (DB) Add function to delete report block
  src/services/reportBlock.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#397 🐛 Fixed published, unpublished and delete draft to return proper access code and work.
  serverless.ts
  src/functions/report/handler.ts
  src/functions/report/index.ts
Labels: priority:high, status:ready, type:bug, role:backend-engineer, scope:backend

#398 ✨ 🗃️ (DB) Add function to get published reports by owner
  src/services/report.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#399 ⚡ ✨ (SERV/API) Add backend code and api endpoint for delete block
  src/functions/report/index.ts
  src/functions/reportBlock/handler.ts
  src/functions/reportBlock/index.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#400 💚 🔥 ✨ (CICD): Enhanced workflows
  .github/workflows/build.yml
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:cicd

#405 🚚 (CICD): Made changes to resources
  .github/workflows/serverless-deploy.yml
  client/src/resources/links.json
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:github-repo, scope:cicd

#406 🔥 (CICD): Updated workflows
  .github/workflows/build.yml
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, type:fix, scope:cicd

#409 🐛 (UI): Fixed View History bug
  client/src/components/ViewHistory/ViewHistory.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:bug

#410 ✨ (UI): Added code for explore page to use real data
  client/src/components/Explore/Explore.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:fix

#411 ⚡ ✨ Added code for get my publish reports function and endpoint
  client/src/auth/PrivateRoute.tsx
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/GetPublishedReport/GetPublishedReport.tsx
  client/src/components/History/History.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Login/Login.tsx
  client/src/components/ReportCard/ReportCard.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/Reports/__tests__/Reports.test.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Text/Text.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
  client/src/resources/links.json
  serverless.ts
  src/functions/report/handler.ts
  src/functions/report/index.ts
  src/functions/reportBlock/handler.ts
  src/services/permission.service.ts
  src/services/report.service.ts
  src/services/reportBlock.service.ts
  src/services/resultSet.service.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#412 Dev/gabriel
  client/src/components/GenReport/GenReport.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#413 🐛 🔥 (API)Changed enpoint to correct endpoint
  src/functions/report/index.ts
Labels: priority:high, status:ready, type:bug, role:backend-engineer, scope:backend

#414 ✨ (CICD/UI): Made changes to DraftCards
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/resources/Report.png
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change

#415 💄 ⚡️ (UI): Added Home UI update
  client/src/components/Home/Home.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#419 🎨 ✨ (UI): Updated report card for explore
  client/src/components/Explore/Explore.tsx
  client/src/components/ExploreCard/ExploreCard.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#420 Dev/ishe
  client/src/components/DraftCard/DraftCard.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change

#421 🔥 (CICD): Made changes to HistoryCard
  client/src/components/HistoryCard/HistoryCard.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:fix

#422 🚀 (CICD): Re-deploying the stack
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:github-repo, scope:cicd

#423 🚑 (CICD): Fixed missing run
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#425 🔥 🗃️ (DB) Change to result set model
  src/model/resultSet/resultSet.model.ts
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:change, role:backend-engineer, scope:backend

#428 🐛 fixing slight bug.
  src/services/report.service.ts
Labels: priority:high, status:ready, type:enhance, type:bug, type:fix, role:backend-engineer, scope:backend

#429 🐛 fixing slight bug.
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, type:change, type:bug, role:backend-engineer, scope:backend

#430 🐛 Fix to get report
  src/functions/report/handler.ts
  src/services/report.service.ts
  src/services/tweet.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:bug, type:fix, role:backend-engineer, scope:backend

#432 ✨ 🔥 (UI): Major changes
  .github/workflows/build.yml
  client/public/assets/logo.jpeg
  client/public/index.html
  client/src/App.tsx
  client/src/auth/PrivateRoute.tsx
  client/src/auth/ProtectedRoutes.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/GetPublishedReport/GetPublishedReport.tsx
  client/src/components/History/History.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Landing/__tests__/Landing.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/MobileNavigation/MobileNavigation.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Text/Text.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
  src/functions/creator/handler.ts
  src/functions/report/handler.ts
  src/services/tweet.service.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:bug, type:fix

#433 (TESTING): Generate report testing
  client/src/components/GenReport/GenReport.tsx
  client/src/components/GetPublishedReport/GetPublishedReport.tsx
  client/src/components/PublishedText/PublishedText.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
  src/functions/report/handler.ts
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:bug, type:fix, scope:backend, role:tester

#434 🐛 (UI): Fixed bug related to drafts page
  client/src/components/Drafts/Drafts.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:fix

#435 💄🔥 ✨ (PWA): Added new logo files + updated margin
  client/public/TS_Logo.ico
  client/public/manifest.json
  client/public/maskable_icon.png
  client/public/maskable_icon_x128.png
  client/public/maskable_icon_x192.png
  client/public/maskable_icon_x384.png
  client/public/maskable_icon_x48.png
  client/public/maskable_icon_x512.png
  client/public/maskable_icon_x72.png
  client/public/maskable_icon_x96.png
  client/src/components/Signup/Signup.tsx
Labels: priority:low, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#436 🔥 🗃️ 🔧 (DB) Changes to creator table definition and remove tweet table
  .github/workflows/serverless-deploy.yml
  serverless.ts
  src/model/creator/index.ts
  src/model/tweet/index.ts
  src/model/tweet/tweet.model.ts
  src/services/__tests__/creator.service.spec.ts
  src/services/creator.service.ts
  src/services/index.ts
  src/services/tweet.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:change, role:backend-engineer, scope:backend

#437 🔧 🚑 🚚 Update dist id and resources
  .github/workflows/serverless-deploy.yml
  client/src/resources/links.json
Labels: priority:high, status:ready, role:team-lead, type:change, role:backend-engineer, scope:github-repo, scope:cicd

#438 🚑 Call default tweet service constructor.
  src/services/index.ts
Labels: priority:high, status:needs-tests, type:fix, role:backend-engineer, scope:backend

#439 ✨ (UI): Added code to get all shared reports
  client/src/components/Shared/Shared.tsx
  client/src/components/SharedCard/SharedCard.tsx
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#440 ⬆️ (CICD): Updated serverless-offline to v8.8.1
  package.json
  yarn.lock
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:cicd

#441 💄 ✨ ⚡️ (UI): Sharing Report Successful
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Shared/Shared.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#442 💄 (UI): Updated logo and maskable files
  .github/workflows/build.yml
  client/public/assets/logo.jpeg
  client/public/assets/logo.png
  client/public/maskable_icon.png
  client/public/maskable_icon_x128.png
  client/public/maskable_icon_x192.png
  client/public/maskable_icon_x384.png
  client/public/maskable_icon_x48.png
  client/public/maskable_icon_x72.png
  client/public/maskable_icon_x96.png
  client/src/components/Logo/Logo.tsx
  client/src/resources/Report.png
Labels: priority:low, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#443 🚚 💄 (ui): Updated logo and maskables
  client/public/assets/logo.png
  client/public/maskable_icon.png
  client/public/maskable_icon_x128.png
  client/public/maskable_icon_x192.png
  client/public/maskable_icon_x384.png
  client/public/maskable_icon_x48.png
  client/public/maskable_icon_x72.png
  client/public/maskable_icon_x96.png
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:change, type:fix

#448 💚 ✨ (CICD): Attempt to fix prettier bug
  .github/workflows/build.yml
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/auth/ProtectedRoutes.tsx
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Explore/Explore.tsx
  client/src/components/ExploreCard/ExploreCard.tsx
  client/src/components/GetPublishedReport/GetPublishedReport.tsx
  client/src/components/History/History.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Landing/__tests__/Landing.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/MobileNavigation/MobileNavigation.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/PublishedText/PublishedText.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/SharedCard/SharedCard.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Text/Text.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
  client/src/resources/links.json
  src/functions/creator/handler.ts
  src/functions/report/handler.ts
  src/functions/resultSet/handler.ts
  src/functions/tweet/handler.ts
  src/model/tweet/tweet.model.ts
  src/services/__tests__/creator.service.spec.ts
  src/services/__tests__/report.service.spec.ts
  src/services/__tests__/reportBlock.service.spec.ts
  src/services/creator.service.ts
  src/services/index.ts
  src/services/report.service.ts
  src/services/tweet.service.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:bug, scope:cicd

#452 💚 ✨(CICD): Testing to see if options worked
  .github/workflows/build.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, scope:cicd

#455 💚 (CICD): Fixed repo and updated workflow
  .github/workflows/build.yml
  .github/workflows/serverless-deploy.yml
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/auth/ProtectedRoutes.tsx
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Explore/Explore.tsx
  client/src/components/ExploreCard/ExploreCard.tsx
  client/src/components/GetPublishedReport/GetPublishedReport.tsx
  client/src/components/History/History.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Landing/__tests__/Landing.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/MobileNavigation/MobileNavigation.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/PublishedText/PublishedText.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/SharedCard/SharedCard.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Text/Text.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
  client/src/resources/links.json
  src/functions/creator/handler.ts
  src/functions/report/handler.ts
  src/functions/resultSet/handler.ts
  src/functions/tweet/handler.ts
  src/model/tweet/tweet.model.ts
  src/services/__tests__/creator.service.spec.ts
  src/services/__tests__/report.service.spec.ts
  src/services/__tests__/reportBlock.service.spec.ts
  src/services/creator.service.ts
  src/services/index.ts
  src/services/report.service.ts
  src/services/tweet.service.ts
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, type:bug, type:fix, scope:cicd

#456 💚 ⚡️ (CICD): Cached dependencies
  .github/workflows/build.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, scope:cicd

#457 🚚 💚 (CICD): Change distributionID & API ID
  .github/workflows/build.yml
  .github/workflows/serverless-deploy.yml
  client/src/App.tsx
  client/src/resources/links.json
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#459 💚(CICD): Fixed Workflow
  .github/workflows/build.yml
  .github/workflows/serverless-deploy.yml
  client/src/App.tsx
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, type:test, scope:cicd

#460 💚 (CICD): testing prettier
  .github/workflows/build.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, type:fix, scope:cicd

#461 💚 (CICD): Fixed deployment
  .github/workflows/build.yml
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#462 🚚✨ (CICD): Caching of yarn packages in deployment + Renamed workflow jobs
  .github/workflows/build.yml
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:cicd

#472 ✅ (TEST) Add unit tests for text styles service
  src/services/__tests__/textStyles.service.spec.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:test, role:backend-engineer, scope:backend, role:tester

#473 ✨ 💄 🔥 (UI): Major changes to the UI
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Home/__tests__/Home.test.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Navigation/Navigation.tsx
Labels: priority:high, status:ready, role:frontend-engineer, type:enhance, scope:cicd

#474 ✨ (UI): Major changes
  .github/workflows/build.yml
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/MobileNavigation/MobileNavigation.tsx
  client/src/components/Shared/Shared.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#475 ⚡️ (UI): Added options to Sharing Report
  client/src/components/GenReport/GenReport.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#478 ✨ (UI): Implemented unpublish report and updated all buttons to use new button component
  client/src/components/Button/Button.tsx
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/GetPublishedReport/GetPublishedReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Home/__tests__/Home.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#479 Dev/ishe
  .github/workflows/build.yml
  .github/workflows/serverless-deploy.yml
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Explore/Explore.tsx
  client/src/components/History/History.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/MobileNavigation/MobileNavigation.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Reports/Reports.tsx
  client/src/resources/links.json
  client/yarn.lock
  serverless.ts
  yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix, scope:github-repo, scope:cicd

#482 💄(UI): Added loading feedback to Search and Generate functionality
  client/src/components/Button/Button.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Navigation/Navigation.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#483 🐛 (UI): Fixed bug in button component for Login and sign up buttons
  client/src/components/Button/Button.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:bug, role:tester

#485 👽️ ✨ 🔥 (UI & API): Major changes to backend and frontend
  .eslintrc.json
  client/package.json
  client/src/App.tsx
  client/src/api/axios.ts
  client/src/components/Button/Button.tsx
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Explore/Explore.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/GetPublishedReport/GetPublishedReport.tsx
  client/src/components/History/History.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/MobileNavigation/MobileNavigation.tsx
  client/src/components/ReportCard/ReportCard.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/Shared/Shared.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
  client/src/components/Text/Text.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
  client/src/editReport.json
  client/src/resources/links.json
  client/yarn.lock
  package.json
  serverless.ts
  src/functions/authorizers/handler.ts
  src/functions/authorizers/index.ts
  src/functions/creator/handler.ts
  src/functions/creator/index.ts
  src/functions/report/index.ts
  src/functions/reportBlock/index.ts
  src/functions/resultSet/index.ts
  src/model/creator/creator.model.ts
  src/services/__tests__/creator.service.spec.ts
  src/services/creator.service.ts
  yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend, scope:cicd

#486 💄 (UI): Added loading feedback for login and signup pages
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#487 💄 (UI): Added loader feedback and animation for draft page
  client/package.json
  client/public/index.html
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/yarn.lock
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#488 🔥 💄 ✨ (UI): Major changes to the UI
  client/src/api/ConfigAxios.ts
  client/src/api/axios.ts
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
  client/src/context/AuthProvider.tsx
  client/src/index.tsx
  client/yarn.lock
  yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#493 💄 (UI): Added loading screen and animation for explore
  client/src/components/Explore.tsx
  client/src/components/ExploreCard.tsx
  client/src/components/GenReport.tsx
  client/src/components/Shared.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#494 🔥 ✨ (UI): Adjustments to Login & SignUp pages + Added redirect from login search
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix

#495 🔥 ✨ (UI): Added logout functionality
  client/src/components/MobileNavigation.tsx
  client/src/components/Navigation.tsx
  client/src/pages/Landing.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix

#496 🔥 (UI): Fixed logout bug
  client/src/pages/Login.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:change, type:fix

#498 🔥 (UI): Fixed console errors for REACT-DOM
  client/src/components/Home.tsx
Labels: status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:change, type:fix

#497 💄 (UI): Added loading feedback and animation to Report Page
  client/src/components/ReportCard.tsx
  client/src/components/Reports.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#499 ✨ (UI): Implemented delete report functionality button inside draft report
  client/src/components/ExploreCard.tsx
  client/src/components/GenReport.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#500 💄 (UI): Added loading feedback and animation to History page
  client/src/components/History.tsx
  client/src/components/HistoryCard.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#489 ✨ 🗃️ 🔧 🚧 (DB) Add new schedule settings table
  serverless.ts
  src/model/schedule/index.ts
  src/model/schedule/schedule.model.ts
  src/services/index.ts
  src/services/schedule.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#503 💄 (UI): See lists of commits in the comment
  client/src/components/History.tsx
  client/src/components/Home.tsx
  client/src/components/Shared.tsx
  client/src/components/SharedCard.tsx
  client/src/components/ViewHistory.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#504 🔥 ✨(UI): Major changes to UI code
  .eslintrc.json
  client/src/api/ConfigAxios.ts
  client/src/components/Button.tsx
  client/src/components/DraftCard.tsx
  client/src/components/Drafts.tsx
  client/src/components/Explore.tsx
  client/src/components/ExploreCard.tsx
  client/src/components/GenReport.tsx
  client/src/components/History.tsx
  client/src/components/HistoryCard.tsx
  client/src/components/Home.tsx
  client/src/components/HomeTweet.tsx
  client/src/components/Logo.tsx
  client/src/components/MobileNavigation.tsx
  client/src/components/Navigation.tsx
  client/src/components/Profile.tsx
  client/src/hooks/useAxiosPrivate.tsx
  client/src/hooks/useRefreshToken.tsx
  client/yarn.lock
  serverless.ts
  src/functions/creator/handler.ts
  src/functions/creator/index.ts
  src/model/creator/creator.model.ts
  src/services/__tests__/creator.service.spec.ts
  yarn.lock
Labels: priority:high, status:ready, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix, scope:cicd

#505 (API/SERV)🐛 get Report fix
  src/functions/report/handler.ts
Labels: priority:high, status:ready, role:team-lead, type:bug, role:backend-engineer, scope:backend

#506 (Dev/gabriel) : Merge conflict fixes
  client/src/components/DraftCard.tsx
  client/src/components/Drafts.tsx
  client/src/components/Explore.tsx
  client/src/components/GenReport.tsx
  client/src/components/GetPublishedReport.tsx
  client/src/components/History.tsx
  client/src/components/HistoryCard.tsx
  client/src/components/Home.tsx
  client/src/components/Navigation.tsx
  client/src/components/Reports.tsx
  client/src/components/Shared.tsx
  client/src/components/ViewHistory.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#508 💄 🔥 ✨(UI): Implemented auth for all pages + Linting
  .eslintrc.json
  client/src/api/ConfigAxios.ts
  client/src/components/Button.tsx
  client/src/components/CLReports.tsx
  client/src/components/DraftCard.tsx
  client/src/components/Drafts.tsx
  client/src/components/ExploreCard.tsx
  client/src/components/GetPublishedReport.tsx
  client/src/components/Home.tsx
  client/src/components/HomeTweet.tsx
  client/src/components/Logo.tsx
  client/src/components/MobileNavigation.tsx
  client/src/components/Profile.tsx
  client/src/components/ReportCard.tsx
  client/src/components/Reports.tsx
  client/src/components/Shared.tsx
  client/src/components/Text.tsx
  client/src/components/ViewHistory.tsx
  client/src/hooks/useAxiosPrivate.tsx
  client/src/hooks/useRefreshToken.tsx
  serverless.ts
  src/functions/creator/handler.ts
  src/functions/creator/index.ts
  src/model/creator/creator.model.ts
  src/services/__tests__/creator.service.spec.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, scope:cicd

#510 ✨ 🗃️ (DB) Add update function for report block
  src/services/reportBlock.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#511 ✨ 🗃️ (DB) Add function to delete text style
  src/services/textStyles.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#513 🔥 💄 ✨ (UI): Major changes - All API calls use axiosPrivate and interceptors
  client/src/api/ConfigAxios.ts
  client/src/components/DraftCard.tsx
  client/src/components/Drafts.tsx
  client/src/components/Explore.tsx
  client/src/components/GenReport.tsx
  client/src/components/GetPublishedReport.tsx
  client/src/components/History.tsx
  client/src/components/HistoryCard.tsx
  client/src/components/Home.tsx
  client/src/components/HomeTweet.tsx
  client/src/components/MobileNavigation.tsx
  client/src/components/Navigation.tsx
  client/src/components/ReportCard.tsx
  client/src/components/Reports.tsx
  client/src/components/Shared.tsx
  client/src/components/SharedCard.tsx
  client/src/components/Text.tsx
  client/src/components/Tweet.tsx
  client/src/components/ViewHistory.tsx
  src/functions/report/index.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#514 ✨ (UI): Updated splash page to display explore page reports & added new home page
  client/src/components/Home.tsx
  client/src/components/Splash.tsx
  src/functions/tweet/index.ts
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#515 💄 🐛🔥 ✨ (UI): Removed localStorage with auth details + fixed re-rending issues
  client/src/components/Drafts.tsx
  client/src/components/GenReport.tsx
  client/src/components/GetPublishedReport.tsx
  client/src/components/History.tsx
  client/src/components/Home.tsx
  client/src/components/MobileNavigation.tsx
  client/src/components/Navigation.tsx
  client/src/components/Reports.tsx
  client/src/components/Shared.tsx
  client/src/components/Text.tsx
  client/src/components/ViewHistory.tsx
  client/src/pages/Login.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#517 🐛 fixing search
  src/functions/tweet/handler.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#518 ✨ (UI): Added code to delete text from draft report
  client/src/components/Text.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#520 ✨ (UI): Updated logo
  client/public/assets/logo.png
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#522 💄 🔥 ✨ (UI): Finished with the Persistent login
  .github/workflows/build.yml
  client/package.json
  client/src/App.tsx
  client/src/auth/RequiredAuth.tsx
  client/src/components/GetPublishedReport.tsx
  client/src/components/MobileNavigation.tsx
  client/src/components/Navigation.tsx
  client/src/components/PersistLogin.tsx
  client/src/components/Splash.tsx
  client/src/context/AuthProvider.tsx
  client/src/hooks/useLogout.tsx
  client/src/hooks/useRefreshToken.tsx
  client/src/pages/Landing.tsx
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
  client/yarn.lock
  package.json
  yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix

#523 🔥 ✨ (CICD/UI): Major changes to frontend & backend
  .github/workflows/build.yml
  client/.eslintignore
  client/.eslintrc.json
  client/.prettierignore
  client/.prettierrc
  client/package.json
  client/src/__tests__/components/Home.test.tsx
  client/src/__tests__/components/Logo.test.tsx
  client/src/__tests__/pages/Landing.test.tsx
  client/src/__tests__/pages/Login.test.tsx
  client/src/__tests__/pages/Signup.test.tsx
  client/src/auth/RequiredAuth.tsx
  client/src/components/Button.tsx
  client/src/components/DraftCard.tsx
  client/src/components/Drafts.tsx
  client/src/components/ExploreCard.tsx
  client/src/components/GenReport.tsx
  client/src/components/GetPublishedReport.tsx
  client/src/components/History.tsx
  client/src/components/Home.tsx
  client/src/components/Navigation.tsx
  client/src/components/ReportCard.tsx
  client/src/components/Reports.tsx
  client/src/components/Shared.tsx
  client/src/components/SharedCard.tsx
  client/src/components/Splash.tsx
  client/src/components/ViewHistory.tsx
  client/src/context/AuthProvider.tsx
  client/src/hooks/useAxiosPrivate.tsx
  client/src/hooks/useLogout.tsx
  client/src/hooks/useRefreshToken.tsx
  client/src/index.tsx
  client/src/pages/Landing.tsx
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
  client/yarn.lock
  serverless.ts
  src/functions/creator/handler.ts
  yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix, scope:cicd

#524 ♻️ 🎨 🔥 (CICD): Formatted files & removed logs
  client/.eslintrc.json
  client/.prettierignore
  client/package.json
  client/src/App.tsx
  client/src/auth/RequiredAuth.tsx
  client/src/components/Button.tsx
  client/src/components/Drafts.tsx
  client/src/components/Home.tsx
  client/src/components/MobileNavigation.tsx
  client/src/components/Navigation.tsx
  client/src/components/PersistLogin.tsx
  client/src/context/AuthProvider.tsx
  client/src/hooks/useLogout.tsx
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
  client/src/resources/links.json
  src/functions/creator/handler.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix, scope:cicd

#525 🐛 🚑 (UI): Fixed logout bug
  client/src/hooks/useLogout.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:bug, type:fix

#526 💄 (UI): Update number of tweets - maybe 5, 10, 15
  client/src/components/Home.tsx
Labels: priority:low, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#527 🔥 (UI): Fixed logout bug
  client/src/components/PersistLogin.tsx
  client/src/hooks/useLogout.tsx
  src/functions/creator/handler.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix

#528 🔥 🚑 🐛 (UI): Fixed refresh bug
  client/src/components/MobileNavigation.tsx
  client/src/components/Navigation.tsx
  client/src/components/PersistLogin.tsx
  client/src/pages/Landing.tsx
  client/src/pages/Signup.tsx
Labels: priority:high, status:ready, role:frontend-engineer, type:change, type:fix, scope:cicd

#529 🔥 (API): Removed authoriser from getReport
  src/functions/report/index.ts
Labels: priority:high, status:ready, role:frontend-engineer, type:enhance, type:change, scope:backend

#530 🐛 (API/SERV) Fix for clone report
  client/.eslintrc.json
  client/.prettierrc
  client/package.json
  client/src/hooks/useLogout.tsx
  client/src/pages/Signup.tsx
  package.json
  serverless.ts
  src/functions/creator/handler.ts
  src/functions/report/handler.ts
  src/functions/resources/APIresponse.ts
  src/functions/schedulers/Functions/report.ts
  src/functions/schedulers/handler.ts
  src/functions/schedulers/index.ts
  src/functions/tweet/handler.ts
  yarn.lock
Labels: priority:high, status:needs-tests, type:bug, type:fix, role:backend-engineer, scope:backend

#531 🐛 ✨ ⚡ 🔥 (API/SERV) Restructured code and changed reorder tweets to work with frontend
  src/functions/tweet/handler.ts
  src/services/reportBlock.service.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#532 🐛 Fix to clone report
  src/functions/report/handler.ts
Labels: priority:high, status:ready, role:team-lead, type:fix, role:backend-engineer, scope:backend

#533 🔥 ⚡ ✨ (API/SERV) Finished reorder tweets
  src/functions/tweet/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, type:change, role:backend-engineer, role:business-analyst, scope:backend

#534 🐛 Fix for reorders.
  src/functions/tweet/handler.ts
Labels: priority:high, status:needs-tests, type:bug, role:backend-engineer, scope:backend

#535 ✨ (UI): Implemented clone report and re-order tweets functionality from frontend
  client/src/components/GenReport.tsx
  client/src/components/GetPublishedReport.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#536 🔥 🗃️ 🐛 ⚰️ 🚑 (DB/SERV) Fix to update report block and reorder tweet
  src/functions/tweet/handler.ts
  src/services/reportBlock.service.ts
Labels: priority:high, status:needs-tests, role:team-lead, type:change, type:bug, type:fix, role:backend-engineer, scope:backend

#537 💄 (UI): DEMO: Add skeleton loader for when lots of tweets are loading on all pages (Home Tweets)
  client/src/components/Home.tsx
  client/src/components/styles/Animation.css
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#538 ✨(UI): Added code to refresh reorderd tweets
  client/src/components/GenReport.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#539 🐛✨ (UI): Fixed re-order tweets for arrow to only display for legal re-order moves
  client/src/components/GenReport.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:bug, type:fix

#540 ✨ (UI): Updated home page to display latest published reports and removed explore navigation
  client/src/__tests__/components/Home.test.tsx
  client/src/components/Home.tsx
  client/src/components/Navigation.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:change

#541 🐛 ♻️ (UI): Made changes to signup and login
  README.md
  client/src/components/Text.tsx
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:change, type:fix

#542 🐛(UI): Fixed re-order tweets bug
  client/src/components/GenReport.tsx
  client/src/components/Navigation.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:bug, type:fix

#544 💄(UI): Please find the list of commits made in the comment
  client/src/components/GenReport.tsx
  client/src/components/GetPublishedReport.tsx
  client/src/components/Home.tsx
  client/src/components/scroll/ScrollToTop.tsx
  client/src/pages/Landing.tsx
  client/src/utils/classNames.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#545 🐛 (API/SERV) Change title for cloned reports and update permissions for get report
  src/functions/report/handler.ts
Labels: priority:high, status:needs-tests, role:team-lead, type:enhance, type:change, type:bug, type:fix, role:backend-engineer, scope:backend

#546 💄(UI): Please find the list of commits made in the comment
  client/src/components/GenReport.tsx
  client/src/components/GetPublishedReport.tsx
  client/src/components/Home.tsx
  client/src/components/ViewHistory.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#548 ✨ 🗃️ ✅ (DB) Add function to delete creator
  src/services/__tests__/permission.service.spec.ts
  src/services/creator.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#547 💄 (UI): Made UI look more elegant
  client/src/components/Drafts.tsx
  client/src/components/Explore.tsx
  client/src/components/GenReport.tsx
  client/src/components/History.tsx
  client/src/components/Home.tsx
  client/src/components/Navigation.tsx
  client/src/components/Reports.tsx
  client/src/components/Shared.tsx
  client/src/pages/Landing.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#543 🐛 ⚰️ 🔥 ⚡ ✅ (TEST) added integration tests
  package.json
  serverless.ts
  src/functions/__tests__/inte/back-end.int.ts
  src/functions/creator/handler.ts
  src/functions/creator/index.ts
  src/functions/report/handler.ts
  src/functions/tweet/handler.ts
  tsconfig.json
  yarn.lock
Labels: priority:high, status:needs-tests, type:test, scope:backend, role:tester

#550 ✅ (UI/TESTING): Updated Login and Sign up Render Unit tests
  client/src/__tests__/pages/Login.test.tsx
  client/src/__tests__/pages/Signup.test.tsx
  client/src/components/Splash.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:fix, type:test, role:tester

#549 🐛 (UI): Fixed persistent login
  client/src/__tests__/components/Home.test.tsx
  client/src/components/Button.tsx
  client/src/components/GenReport.tsx
  client/src/components/PersistLogin.tsx
  client/src/context/AuthProvider.tsx
  client/src/hooks/useAxiosPrivate.tsx
  client/src/hooks/useRefreshToken.tsx
  client/src/pages/Signup.tsx
  src/functions/creator/handler.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:change, type:fix
