Repository COS301-SE-2022/Twitter-Summariser, pull requests merged in 2022-05, with the labels that each got.

#2 (GitHub): Code Quality Badges
  README.md
Labels: priority:high, status:not-ready, role:dev-op, type:change, scope:github-repo

#9 Updated Project Setup
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: priority:high, status:ready, role:ui-engineer, scope:github-repo

#12 Added Jonah Bio to README
  README.md
  package-lock.json
Labels: priority:medium, status:ready, scope:github-repo

#19 ✨ Add main component files for authorization pages
  client/package-lock.json
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/components/authorization-components/LoginBody.tsx
  client/src/components/authorization-components/LoginHeader.tsx
  client/src/components/authorization-components/SignUpBody.tsx
  client/src/components/authorization-components/SignUpHeader.tsx
  client/src/css/App.css
  client/src/css/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/pages/AuthorizationPage.tsx
  client/src/pages/LandingPage.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#21 ✨ Add main component files for landing page
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.tsx
  client/src/components/common-components/NavBar.tsx
  client/src/components/common-components/SearchBar.tsx
  client/src/components/landing-components/DraftReports.tsx
  client/src/components/landing-components/LandingBody.tsx
  client/src/components/landing-components/LandingHeader.tsx
  client/src/css/App.css
  client/src/pages/LandingPage.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#20 ✨ (hosting): CDK Hosting Added
  client/package-lock.json
  client/package.json
  infrastructure/bin/infrastructure.ts
  infrastructure/lib/infrastructure-stack.ts
  infrastructure/package-lock.json
  infrastructure/package.json
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:github-repo

#22 📦 Added styling files (Tailwindcss)
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/App.tsx
  client/src/css/index.css
  client/tailwind.config.js
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:change

#23 ✨ (Lint): Added ESLint for frontend
  client/.eslintignore
  client/.eslintrc.json
  client/.prettierignore
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/components/authorization-components/LoginBody.tsx
  client/src/components/authorization-components/LoginHeader.tsx
  client/src/components/authorization-components/SignUpBody.tsx
  client/src/components/authorization-components/SignUpHeader.tsx
  client/src/components/common-components/NavBar.tsx
  client/src/components/common-components/SearchBar.tsx
  client/src/components/landing-components/DraftReports.tsx
  client/src/components/landing-components/LandingBody.tsx
  client/src/components/landing-components/LandingHeader.tsx
  client/src/css/App.css
  client/src/index.tsx
  client/src/pages/AuthorizationPage.tsx
  client/src/pages/LandingPage.tsx
  client/src/reportWebVitals.ts
  client/tailwind.config.js
  client/tsconfig.json
Labels: priority:medium, status:ready, scope:frontend, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#25 🚧 ✨ (CICD): Added the workflow for frontend
  .github/workflows/frontend.yml
Labels: priority:high, status:not-ready, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#27 Malcolm readme section
  README.md
Labels: priority:medium, status:ready, scope:github-repo

#26 🚑 (CICD): Fixed naming convention
  .github/workflows/frontend.yml
  client/src/App.tsx
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#28 Adding another badge
  README.md
Labels: priority:low, status:ready, type:documentation, role:backend-engineer, scope:github-repo

#29 ✨ (CICD): Added coveralls
  .github/workflows/frontend.yml
  client/package-lock.json
  client/package.json
  client/src/components/authorization-components/LoginBody.tsx
  client/src/components/authorization-components/LoginHeader.tsx
  client/src/components/authorization-components/SignUpBody.tsx
  client/src/components/authorization-components/SignUpHeader.tsx
  client/src/components/common-components/NavBar.tsx
  client/src/components/common-components/SearchBar.tsx
  client/src/components/landing-components/DraftReports.tsx
  client/src/components/landing-components/LandingBody.tsx
  client/src/components/landing-components/LandingHeader.tsx
  client/src/pages/AuthorizationPage.tsx
  client/src/pages/LandingPage.tsx
Labels: priority:medium, status:needs-tests, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#30 🔥 (CICD): Minor changes to React worfklow file
  .github/workflows/frontend.yml
  client/package.json
  client/postcss.config.js
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#31 🐛 (CICD): Minor changes
  .github/workflows/frontend.yml
Labels: priority:medium, status:needs-tests, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#35 ✨ 🔥 (CICD): Made changes to eslint
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/components/common-components/NavBar.tsx
Labels: priority:high, status:ready, scope:frontend, role:dev-op, type:fix, scope:github-repo, scope:cicd

#36 🐛:(UI) Adding structure for the tweet
  client/public/assets/logo.png
  client/src/App.tsx
  client/src/components/Landing/Landing.css
  client/src/components/Landing/Landing.tsx
  client/src/components/Landing/__tests__/Landing.test.tsx
  client/src/components/Login/Login.css
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Logo/Logo.css
  client/src/components/Logo/Logo.tsx
  client/src/components/Logo/__tests__/Logo.test.tsx
  client/src/components/Navigation/Navigation.css
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Navigation/__tests__/Navigation.test.tsx
  client/src/components/Signup/Signup.css
  client/src/components/Signup/Signup.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
  client/src/components/authorization-components/LoginBody.tsx
  client/src/components/authorization-components/LoginHeader.tsx
  client/src/components/authorization-components/SignUpBody.tsx
  client/src/components/authorization-components/SignUpHeader.tsx
  client/src/components/common-components/NavBar.tsx
  client/src/components/common-components/SearchBar.tsx
  client/src/components/landing-components/DraftReports.tsx
  client/src/components/landing-components/LandingBody.tsx
  client/src/components/landing-components/LandingHeader.tsx
  client/src/css/App.css
  client/src/css/index.css
  client/src/index.css
  client/src/index.tsx
  client/src/pages/AuthorizationPage.tsx
  client/src/pages/LandingPage.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:fix, type:test

#37 🔥 ✨ (CICD): Made new entire workflow
  .github/workflows/frontend.yml
  .github/workflows/full.yml
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#39 ✨ (CICD): Ignore json files
  client/.eslintignore
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#38 🐛 🤡 (UI): Added mock data files and also fixed a bug
  client/.prettierrc.json
  client/src/mock.json
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:test, role:designer

#40 ✨ (CICD): Changes to full.yml
  .github/workflows/full.yml
  client/.eslintignore
  client/.eslintrc.json
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#42 ⚡️ (UI): Added search functionality for mock data
  client/package.json
  client/src/components/Landing/Landing.tsx
  client/src/mock.json
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:documentation, type:test, role:designer

#41 Feature/cicd
  .github/workflows/full.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, scope:github-repo, scope:cicd

#43 🐛 (CICD): Fixed a bug
  .github/workflows/full.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:github-repo, scope:cicd

#44 🎨 (CICD): Changed Workflow Name
  .github/workflows/full.yml
Labels: priority:high, status:ready, role:dev-op, type:change, scope:github-repo, scope:cicd

#45 ✨ (CICD): Added the build badge
  README.md
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#48 🔥 (CICD): Add new rule
  client/.eslintrc.json
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#49 🐛 (CICD): Fixed an env issue
  .github/workflows/full.yml
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:cicd

#50 🐛 (CICD): fix
  .github/workflows/full.yml
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#47 🚸 💄 🎨 (UI): Converted Home specific containers to Home Components
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Navigation/Navigation.tsx
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, type:test, role:designer

#52 🐛 (CICD): minor fix
  client/.eslintrc.json
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:github-repo, scope:cicd

#53 🐛 Minor fix
  client/.eslintrc.json
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:cicd

#51 🚸 💄 🎨 (UI): Added buttons to the Navigation
  client/src/components/CLReports/CLReports.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Explore/Explore.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Profile/Profile.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/Shared/Shared.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:documentation, type:test, role:designer

#54 ✨ 🔥 (CICD): Major changes to prettier and eslint
  client/.eslintrc.json
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/CLReports/CLReports.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/Explore/Explore.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Landing/__tests__/Landing.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Profile/Profile.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/Shared/Shared.tsx
  client/src/components/Signup/Signup.tsx
  client/src/index.tsx
  client/src/reportWebVitals.ts
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:fix, scope:cicd

#55 🚸 💄 ⚡️ 🎨 (UI): Added UI to "My Report" component
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Reports/Reports.tsx
  client/src/mock.json
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, type:test, role:designer

#56 ✨ (CICD): Added coveralls to workflow
  .github/workflows/coverage.yml
  .github/workflows/full.yml
  README.md
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Logo/__tests__/Logo.test.tsx
  client/src/components/Navigation/__tests__/Navigation.test.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
  client/tailwind.config.js
Labels: priority:high, status:needs-tests, role:dev-op, type:change, scope:github-repo, scope:cicd

#57 ✨ (CICD): Added code coverage badge
  .github/workflows/coverage-client.yml
  .github/workflows/full.yml
  README.md
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#59 🚸 🚧 📝 ⚡️ 🎨 (UI): Added UI to Explore component
  client/src/components/Explore/Explore.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Reports/Reports.tsx
  client/src/mock.json
  client/tailwind.config.js
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:documentation, type:fix, type:test, role:tester, role:designer

#60 ✨ Added Mock generate report functionality
  client/package-lock.json
  client/package.json
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#61 ✨ (CICD): Removed a jest rule
  client/.eslintrc.json
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:fix, scope:cicd

#62 🚸 💄 ⚡️ 🎨 (UI): Added Logo to title bar and also update the title
  client/package-lock.json
  client/public/index.html
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:test, role:designer

#63 33 unit testing
  client/src/components/Explore/Explore.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Home/__tests__/Home.test.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Reports/Reports.tsx
Labels: priority:high, status:ready, scope:frontend, type:test, role:backend-engineer, role:tester

#64 ✅ merging working Tests for report component: working
  client/src/components/Reports/Reports.tsx
  client/src/components/Reports/__tests__/Reports.test.tsx
Labels: priority:high, status:ready, scope:frontend, type:test, role:backend-engineer, role:tester

#65 ✅ :merging working Tests for other component: working
  client/src/components/Home/__tests__/Home.test.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Landing/__tests__/Landing.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/Logo/__tests__/Logo.test.tsx
  client/src/components/Reports/__tests__/Reports.test.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
Labels: priority:medium, status:ready, scope:frontend, type:test, role:backend-engineer, role:tester

#66 📝 Update README.md
  README.md
Labels: priority:high, status:ready, role:team-lead, type:documentation, scope:github-repo

#67 Changing Picture
  README.md
Labels: priority:high, status:ready, type:change, type:documentation, role:backend-engineer, scope:github-repo

#68 ✨ (CICD): Added working code from develop to master
  .github/workflows/coverage-client.yml
  .github/workflows/full.yml
  README.md
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/Explore/Explore.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Home/__tests__/Home.test.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Landing/__tests__/Landing.test.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/Logo/__tests__/Logo.test.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Navigation/__tests__/Navigation.test.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/Reports/__tests__/Reports.test.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
  client/src/mock.json
  client/tailwind.config.js
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#70 🚑 (CICD): Removed lint test
  .github/workflows/full.yml
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#69 🚸 🚧 🚀 ⚡️ 🎨 ✨ (Added the Login Component)
  client/.eslintignore
  client/.eslintrc.json
  client/.prettierignore
  client/.prettierrc.json
  client/src/App.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/Login.css
  client/src/components/Login/Login.tsx
  client/src/components/Logo/Logo.css
  client/src/components/Logo/Logo.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:documentation, type:test, role:designer

#71 🚸 🚧 🚀 ⚡️ 🎨 ✨ (UI): Added the Login Component Functionality
  client/src/App.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/Login.css
  client/src/components/Login/Login.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/mock.json
Labels: priority:high, status:ready, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:documentation

#72 🚑 (UI) : Fixed authentication issues to accomodate either email or username
  client/src/App.tsx
Labels: priority:high, status:ready, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:documentation, type:fix, role:designer

#73 🚸 🚧 🚀 ⚡️ 🎨 ✨(UI): Added the Signup Component
  client/src/App.tsx
  client/src/components/Signup/Signup.css
  client/src/components/Signup/Signup.tsx
Labels: priority:high, status:ready, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:documentation, type:test, role:tester, role:designer

#74 ✅ Added basic render and input field unit tests for login and sign up components
  client/src/components/Login/Login.tsx
  client/src/components/Login/__tests__/Login.test.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Signup/__tests__/Signup.test.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:test, role:tester

#79 🚸 🚧 🚀 ⚡️ 🎨 ✨(UI): Interface for generate report webpage generated
  client/src/components/Home/Home.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:documentation, role:designer

#80 🚸 💄 (UI): Added a little bit of responsiveness
  client/src/components/Explore/Explore.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/Navigation/Navigation.tsx
  client/tailwind.config.js
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#93 💄 🚑 ⚡️ 🎨 (UI): Added more search functionality and added new button
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.css
  client/src/App.test.tsx
  client/src/components/Home/Home.tsx
  client/src/logo.svg
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:documentation, type:test, role:designer

#94 💄 ✨ ⚡️ 🎨 (UI): Added Tweet component
  client/package-lock.json
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Tweet/Tweet.tsx
  client/src/index.tsx
  client/src/mock.json
  client/yarn.lock
Labels: priority:high, status:ready, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#95 🔥 ✨ (CICD): Hosting up and running
  client/README.md
  serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:github-repo, scope:cicd

#97 ✨ (CICD): Added serverless deploy workflow
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, scope:cicd

#98 🐛 (CICD): Fix for flow skip
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#107 ✨ (CICD): Full workflow 80% complete
  .github/workflows/main.yml
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, scope:cicd

#109 ✨ (CICD): Fixed a deployment error
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#108 ✨ 🗃️ 🔧 🎨 Creator table created
  docker-compose.yml
  jest.int.config.js
  jest.unit.config.js
  package.json
  serverless.ts
  src/functions/creator/handler.ts
  src/model/creator.model.ts
  src/model/database.ts
  src/model/index.ts
  src/services/creator.service.ts
  tsconfig.paths.json
  yarn.lock
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#110 🚑 (UI): adjusting the filter and sorting options
  client/src/components/Home/Home.tsx
Labels: priority:high, priority:medium, status:ready, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#111 🐛 (CICD): Changed workflow name
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#112 ✨ (CICD): Made changes to README & workflow name
  .github/workflows/serverless-deploy.yml
  README.md
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:cicd

#113 ⚡️ (UI): Adding default select options
  client/src/components/Home/Home.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#114 ✨ 🗃️ 🔧 signup and login api types complete
  README.md
  serverless.ts
  src/functions/creator/handler.ts
  src/functions/creator/index.ts
  src/model/index.ts
  src/services/creator.service.ts
Labels: priority:medium, status:needs-tests, scope:db, role:team-lead, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#99 ✅ Added unit tests for Home Page
  client/src/components/Home/Home.tsx
  client/src/components/Home/__tests__/Home.test.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:test, role:tester

#115 🔥 🐛 (CICD): Major fix of Serverless Wrokflow
  .github/workflows/main.yml
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#116 🔧 🗃️ run local tables on docker
  .gitignore
  package.json
  serverless.ts
  src/functions/clients/twitterV2.client.ts
  src/functions/model/tweet.model.ts
  src/functions/search/handler.ts
  src/functions/search/index.ts
  src/functions/trending/handler.ts
  src/functions/trending/index.ts
  src/model/creator/creator.model.ts
  src/model/creator/index.ts
  src/model/database.ts
  src/services/creator.service.ts
  yarn.lock
Labels: priority:high, status:ready, scope:db, role:team-lead, type:change, type:bug, type:fix

#117 ✨ Added react routing to landing page
  client/package.json
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/PageNotFound/PageNotFound.tsx
  client/yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#119 ✨ (CICD): Code to not treat warnings as errors
  .github/workflows/serverless-deploy.yml
  README.md
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#120 🔥 ✨ (CICD): Added new badges & refactored code
  README.md
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:github-repo, scope:cicd
