Repository COS301-SE-2022/Twitter-Summariser, pull requests merged in 2022-06, with the labels that each got.

#127 🔥 (CICD): Removed webpack
  package.json
  serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#128 ✨ 🗃️ 🔧 ➕ result set table creation
  babel.config.js
  jest.int.config.js
  jest.unit.config.js
  package.json
  serverless.ts
  src/model/resultSet/index.ts
  src/model/resultSet/resultSet.model.ts
  src/services/__tests__/creator.service.int.ts
  src/services/creator.service.ts
  src/services/resultSet.service.ts
  yarn.lock
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#131 ✨ (UI): Added the logout functionality
  client/src/components/Landing/Landing.tsx
  client/src/components/Navigation/Navigation.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#133 ✨ 🎨 ⚡️ (UI): Added a new functionality
  client/src/App.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
Labels: priority:medium, status:ready, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#135 💄 ✨ ⚡️ 🎨 (UI): Added new component called text
  client/package.json
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Text/Text.tsx
  client/src/components/Tweet/Tweet.tsx
  client/src/editReport.json
  client/yarn.lock
  package.json
  yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#136 🐛 ⚡️(CICD): Attempt to fix hosting URL
  serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#138 ✨Added in course header
  src/functions/search/handler.ts
Labels: priority:high, status:ready, type:bug, role:backend-engineer, scope:backend

#139 🚑 (CICD): Fixed Domain name
  serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#140 🔀 🐛 ixing Return of search Function
  src/functions/search/handler.ts
Labels: priority:high, status:not-ready, type:enhance, role:backend-engineer, scope:backend

#141 🚧 💄 ✨ 🎨 (UI): Added the History page to the navigation
  client/src/components/History/History.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Navigation/Navigation.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#142 ✨ (API): Aded CORS to HTTP
  src/functions/creator/index.ts
  src/functions/search/index.ts
  src/functions/trending/index.ts
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:backend

#143 ✨ 🔥 (API): Made changes to the getAllCreators
  src/functions/creator/handler.ts
  src/functions/creator/index.ts
Labels: priority:high, status:needs-tests, scope:ai, role:dev-op, type:change, type:fix

#144 :zap::bug:Added response headers to search function
  src/functions/search/handler.ts
Labels: priority:high, status:ready, type:bug, role:backend-engineer, scope:backend

#145 🔥 ♻️ (API): Made a reponseHeaders object + removed unused imports
  src/functions/creator/handler.ts
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:backend

#147 ⚡ ✨ 🚀 Finailsed the search function added in API key and fliter options and writing to DB
  src/functions/search/handler.ts
  src/model/FrontEndResponse/search.ts
  src/model/resultSet/resultSet.model.ts
  src/services/index.ts
Labels: priority:high, status:ready, type:bug, role:backend-engineer, scope:backend

#149 💄 ✨ ⚡️ 🎨 (UI): Linked frontend with api
  client/src/App.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Navigation/Navigation.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Tweet/Tweet.tsx
  client/src/index.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#150 🐛 ⚡ ✨ 🎨 🔥 📝 ♻️ 🔧 🔨 🚚 🍱 💡 🚸 🗑️ ⚰️ 🧑‍💻 Quite a big PR
  serverless.ts
  src/functions/TweetTransServices/tweet.service.ts
  src/functions/creator/index.ts
  src/functions/generateReport/handler.ts
  src/functions/generateReport/index.ts
  src/functions/report/handler.ts
  src/functions/report/index.ts
  src/functions/resultSet/handler.ts
  src/functions/resultSet/index.ts
  src/functions/search/handler.ts
  src/functions/search/index.ts
  src/model/FrontEndResponse/search.ts
  src/model/Report/report.model.ts
  src/model/tweet/tweet.model.ts
  src/services/index.ts
  src/services/report.service.ts
  src/services/resultSet.service.ts
  src/services/tweet.service.ts
Labels: priority:high, status:needs-tests, type:enhance, type:change, type:bug, type:documentation, type:fix, role:backend-engineer, scope:backend

#153 Added console log for debugging
  client/src/components/Login/Login.tsx
  client/src/components/Splash/Splash.css
  client/src/components/Splash/Splash.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#155 ✨ 🗃️ ✏️ 🐛 🔧 Creation of report table, fix to search endpoint
  serverless.ts
  src/functions/generateReport/handler.ts
  src/functions/report/handler.ts
  src/functions/resultSet/handler.ts
  src/functions/search/handler.ts
  src/model/report/index.ts
  src/model/report/report.model.ts
  src/model/tweet/tweet.model.ts
  src/services/report.service.ts
  src/services/resultSet.service.ts
  src/services/tweet.service.ts
Labels: priority:high, status:ready, status:needs-tests, scope:db, type:enhance, type:change, type:bug, type:fix, role:backend-engineer, scope:backend, role:tester

#158 🚑 🐛 (CICD): Code to fix hanging deployment
  .github/workflows/main.yml
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#159 🐛 (CICD):Major fix
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#161 🐛 (CICD): Attempt to fix hanging workflow
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#162 🔥 (CICD): Change everything back to normal
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#163 💄 ✨ 🎨 ⚡️(UI): Login and signup endpoint added
  client/src/App.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
Labels: priority:high, priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#164 💄 ✨ ⚡️ 🎨(UI): Added endpoint to Search
  client/src/components/Home/Home.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#165 🐛 (CICD): Major update - Fix hanging workflow
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:enhance, scope:cicd

#168 🔥 (CICD): Fixed Coveralls
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:fix, scope:cicd

#166 🗃️ added title to generate report
  src/functions/generateReport/handler.ts
  src/model/report/report.model.ts
Labels: priority:high, status:ready, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#170 ✨ (CICD): Coverage report for backend
  .github/workflows/serverless-deploy.yml
  .gitignore
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:fix, scope:cicd

#172 ✨ Fixed Routing for all components
  client/src/App.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Splash/Splash.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#174 💄 ✨ ⚡️ 🎨(UI): Linked Gen Report page with endpoint
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
Labels: priority:high, priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, role:designer

#173 🔥 ✨ (CICD): Added new coverage workflow
  .github/workflows/backend-coverage.yml
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, scope:cicd

#175 ✨ (CICD): Backend coverage
  .github/workflows/backend-coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#176 ✨ (CICD): Added backend code coverage badge
  README.md
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#181 ✅ 🔥 (DB/TEST) unit tests for creator table and report table
  src/__mocks__/aws-sdk.ts
  src/services/__tests__/creator.service.spec.ts
  src/services/__tests__/report.service.spec.ts
  src/services/report.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:test, role:backend-engineer, scope:backend, role:tester

#183 💚 ✨ 🔥 (CICD): Changed workflow for code coverage
  .github/workflows/coverage.yml
  tools/scripts/merge-reports.js
  tools/tsconfig.tools.json
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:cicd

#184 🐛 (CICD): Fixed a bug with the coverage workflow
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#185 🐛 (CICD): Fixed package dependecy for coverage
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#187 🐛(UI/Routing): Fixed routing bugs for all components
  client/src/App.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/Splash/Splash.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:bug

#186 🐛 Fixed time zone.
  src/functions/generateReport/handler.ts
  src/functions/search/handler.ts
Labels: priority:medium, status:ready, type:bug, role:backend-engineer, scope:backend

#188 🐛 (CICD): Attempted fix for merge reports
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:fix, scope:github-repo, scope:cicd

#189 🐛 (CICD): Major fix
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:github-repo, scope:cicd

#190 🐛 (CICD): Minor fix
  tools/scripts/merge-reports.js
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#191 🔥 (CICD): Fix minor issue
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:fix, scope:cicd

#192 🐛 (CICD): Fix minor issue
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:fix, scope:cicd

#193 ✨ 🗃️ 🔧 (DB) add report block table
  serverless.ts
  src/model/reportBlock/index.ts
  src/model/reportBlock/reportBlock.model.ts
  src/services/reportBlock.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance

#194 ✏️ 🗃️ 🔧 fixed typo
  src/model/reportBlock/index.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:fix

#195 ✨ 🔥 (CICD): Coverage for frontend and backend
  .github/workflows/coverage.yml
  client/.gitignore
  tools/scripts/merge-reports.js
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, type:fix, scope:cicd

#196 🐛 (CICD): Minor fix
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#197 🚧 (CICD): Testin g to see contents of lcov file
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#198 🗃️ ✏️ (DB) change to report block model
  src/model/reportBlock/reportBlock.model.ts
  src/services/reportBlock.service.ts
Labels: priority:high, status:ready, scope:db, type:change, type:fix, role:tester

#199 🔥 🐛 (CICD): Put console log at the wrong place
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#200 ✨ 🗃️ 🔧 add new table TextStylesTable
  serverless.ts
  src/model/report/report.model.ts
  src/model/textStyles/index.ts
  src/model/textStyles/textStyles.model.ts
  src/services/reportBlock.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, type:change, role:backend-engineer, scope:backend

#202 ✨ (UI/PWA): Added PWA service worker components
  client/public/logo192.png
  client/public/logo512.png
  client/src/index.tsx
  client/src/service-worker.ts
  client/src/serviceWorkerRegistration.ts
  package.json
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#203 ✨ (UI/PWA): Added logo icon to manifest
  client/public/TS_Logo.ico
  client/public/manifest.json
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#204 ✨ (CICD): New depencies & made changes to workflow
  .github/workflows/coverage.yml
  README.md
  package.json
  yarn.lock
Labels: priority:high, status:ready, status:needs-tests, role:dev-op, type:enhance, type:change, scope:cicd

#205 🐛 ❇️ Fixed date error and added block sorting
  serverless.ts
  src/functions/editBlock/handler.ts
  src/functions/editBlock/index.ts
  src/functions/generateReport/handler.ts
  src/functions/report/handler.ts
  src/functions/search/handler.ts
  src/model/report/report.model.ts
  src/model/resultSet/resultSet.model.ts
  src/services/index.ts
  src/services/reportBlock.service.ts
Labels: priority:high, status:needs-tests, type:change, type:bug, role:backend-engineer, scope:backend

#206 🔥 🚚 (CICD): Attempt to upload frontend coverage
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:test, scope:cicd

#207 🐛 ⚡ Added in sort.
  src/services/reportBlock.service.ts
Labels: priority:high, status:ready, scope:ai, type:change, type:bug, role:backend-engineer, scope:backend

#208 🔥 (CICD): Changed syntax error in workflow
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:fix, type:test, scope:cicd

#210 🔥(CICD): Deleted failing test & Changed workflow
  .github/workflows/main.yml
  src/services/__tests__/report.service.spec.ts
  src/services/reportBlock.service.ts
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:fix, scope:cicd

#209 ✨ (UI): Populated History page with API data
  client/src/components/History/History.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#211 ✨ (UI): Created History card component and passed div into it
  client/src/components/History/History.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Home/Home.tsx
Labels: priority:low, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#212 🔥 🗃️ 🔧 🐛 (DB) (BACKEND) change structure of report object
  src/functions/generateReport/handler.ts
  src/functions/report/handler.ts
  src/model/reportBlock/index.ts
  src/model/reportBlock/reportBlock.model.ts
  src/model/tweet/index.ts
  src/services/index.ts
  src/services/report.service.ts
  src/services/reportBlock.service.ts
  src/services/textStyles.service.ts
  src/services/tweet.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, type:change, type:bug, type:fix, role:backend-engineer, scope:backend

#213 ✨ 🔥 🗃️ (BACKEND) Add update text endpoint to api
  src/functions/editBlock/handler.ts
  src/functions/generateReport/handler.ts
  src/model/textStyles/textStyles.model.ts
Labels: priority:high, status:needs-tests, scope:db, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#215 🚑 (UI): Changed the some endpoints for Team members testing
  client/src/App.tsx
  client/src/components/History/History.tsx
  client/src/components/HistoryCard/HistoryCard.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#216 ✅ add unit tests for Creator and Report tables
  src/services/__tests__/creator.service.spec.ts
  src/services/__tests__/report.service.spec.ts
  src/services/report.service.ts
  src/services/reportBlock.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:change, type:test, role:backend-engineer, scope:backend, role:tester

#217 ✨ (UI): Retrieving data from API and Created new components
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/History/History.tsx
  client/src/components/Home/Home.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#219 ✨ (UI): Retreiving data from Get Report API
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Text/Text.tsx
  client/src/components/Tweet/Tweet.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#220 ✨ (UI/PWA): Added TS icons to manifest
  client/public/TS_Logo_128x128.png
  client/public/TS_Logo_16x16.png
  client/public/TS_Logo_24x24.png
  client/public/TS_Logo_256x256.png
  client/public/TS_Logo_32x32.png
  client/public/TS_Logo_48x48.png
  client/public/manifest.json
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#222 ✨ (UI): Created new Tweet components for Home page
  client/src/components/Home/Home.tsx
  client/src/components/HomeTweet/HomeTweet.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#223 🚧 (CICD): Attempt to upload frontend coverage
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#224 🗃️ ✏️ change text style index
  src/services/textStyles.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:bug, type:fix, scope:backend

#225 🐛 (CICD): Minor fix
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:test, scope:cicd

#226 🐛 (CICD): Attempt to upload frontend coverage
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:test, scope:cicd

#227 🐛 (CICD): Attempt to fix lcov not found
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:bug, type:test, scope:cicd

#228 🐛 (CICD): Testing frontend deployment
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, type:test, scope:cicd

#229 🐛 (CICD): Fix frontend
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#230 🔥 (CICD): Testing frontend coverage
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:test, scope:cicd

#231 🔥(CICD): Testing
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:test, scope:cicd

#233 🚧 (CICD): Testi if frontend coverage is uploaded
  .github/workflows/coverage.yml
  README.md
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:test, scope:cicd

#234 ✨ (UI): Updated email input on login page
  client/public/manifest.json
  client/src/components/Login/Login.tsx
  client/src/components/Signup/Signup.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:fix

#235 🐛 ⚡ Added null values
  jest.unit.config.js
  package.json
  src/functions/report/handler.ts
  src/services/__tests__/report.service.spec.ts
  src/services/report.service.ts
  yarn-error.log
  yarn.lock
Labels: priority:high, status:ready, type:change, type:bug, role:backend-engineer, scope:backend

#238 ✨ (UI): Added Data from API to resultSet, Generate report from result…
  client/src/App.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/Text/Text.tsx
  client/src/components/Tweet/Tweet.tsx
  client/src/components/ViewHistory/ViewHistory.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#239 ✅ (DB/TEST) add unit tests for result set table
  src/services/__tests__/resultSet.service.spec.ts
  src/services/resultSet.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:change, type:test, role:backend-engineer, scope:backend, role:tester

#237 🎨 🔥 (CICD): Reverted the coverage workflow
  .github/workflows/coverage.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#240 ✨ (UI): We added custom styles, custom texts and fixed the bugs ...
  client/src/components/DraftCard/DraftCard.tsx
  client/src/components/Drafts/Drafts.tsx
  client/src/components/GenReport/GenReport.tsx
  client/src/components/History/History.tsx
  client/src/components/Home/Home.tsx
  client/src/components/Text/Text.tsx
  client/src/components/Tweet/Tweet.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#241 🐛 ⚡ Add default tiltle as the search phrase
  jest.unit.config.js
  package.json
  src/functions/__tests__/inte/creator.handler.int.ts
  src/functions/generateReport/handler.ts
  src/services/report.service.ts
  yarn.lock
Labels: priority:high, status:ready, type:bug, role:backend-engineer, scope:backend

#243 🔥 🔧 🎨 ✅ ➕ (TEST) change config file of jest tests
  jest.config.js
  jest.int.config.js
  package.json
  src/functions/__tests__/inte/creator.handler.int.ts
  src/services/__tests__/creator.service.int.ts
  yarn.lock
Labels: priority:high, status:ready, type:change, type:test, role:backend-engineer, scope:backend

#244 🧪 Added integration to test that test various api endpoints
  src/functions/__tests__/inte/creator.handler.int.ts
  src/functions/__tests__/inte/editblock.handler.int.ts
  src/functions/__tests__/inte/generateReport.handler.int.ts
  src/functions/creator/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, type:bug, role:backend-engineer, scope:backend, role:tester

#246 Delete creator.handler.int.ts
  src/functions/__tests__/inte/creator.handler.int.ts
Labels: priority:high

#248 🐛 💚 (CICD/Deploy): Fixed indentation in workflow
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:cicd

#249 🐛 (CICD): Fixed failing workflow
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#250 🚑 (CICD): Attempt to fix failing invalidation
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#251 🚑 (CICD): Attempt to fix failing invalidation
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#252 🚑 (CICD): Attempt to fix failing invalidation
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#253 📝 (DOC) update readMe
  README.md
Labels: priority:high, status:ready, role:team-lead, type:documentation, scope:github-repo

#254 🚑 (CICD): Attempt to fix failing invalidation
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#255 🚑 (CICD): Attempt to fix failing invalidation
  .github/workflows/serverless-deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#272 🚑 (UI): Fixed margin issues on gen report page
  client/src/components/GenReport/GenReport.tsx
Labels: priority:medium, priority:low, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#295 💚 ✨ (CICD): Excluded some paths for backend test
  .github/workflows/main.yml
Labels: priority:low, status:needs-tests, role:dev-op, type:enhance, scope:cicd

#296 🎨 ✨ Added clone report endpoint as well as restructured backend/API to be object oriented, as well as changed certain endpoints.
  serverless.ts
  src/functions/generateReport/handler.ts
  src/functions/generateReport/index.ts
  src/functions/report/handler.ts
  src/functions/report/index.ts
  src/functions/reportBlock/handler.ts
  src/functions/reportBlock/index.ts
  src/functions/trending/handler.ts
  src/functions/trending/index.ts
  src/functions/tweet/handler.ts
  src/functions/tweet/index.ts
Labels: priority:high, status:ready, type:change, type:bug, type:fix, role:backend-engineer, scope:backend

#297 ✨ added publish report function.
  serverless.ts
  src/functions/report/handler.ts
  src/functions/report/index.ts
Labels: priority:high, status:ready, type:enhance, type:bug, role:backend-engineer, scope:backend

#310 :construction: :card_file_box: add attribute to report model
  src/functions/report/handler.ts
  src/model/report/report.model.ts
  src/services/__tests__/report.service.spec.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:change, type:fix, role:backend-engineer, scope:backend

#312 ✨ 🗃️ (DB) Add update function for report status attribute
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#313 ✨ 🗃️ (DB) Add delete operation for a result set
  src/services/resultSet.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#318 ✨ 🔒 Finished code for endpoints
  src/functions/report/handler.ts
  src/services/report.service.ts
Labels: priority:high, status:needs-tests, type:enhance, type:change, role:backend-engineer, scope:backend

#320 🚑 (CICD): Added path to lcov
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#324 ✨ (CICD): Attempt to use codecov instead of coveralls
  .github/workflows/coverage.yml
  README.md
Labels: priority:high, status:needs-tests, role:dev-op, type:change, scope:cicd

#326 ⚡️ ✨ Major changes to the coverage workflow
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, type:fix, scope:cicd

#327 🚑 (CICD): Typo fix
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#328 🚑 (CICD): Typo fix
  .github/workflows/coverage.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#329 📝 🔥 ✨ (CICD): Updated README & coverage badge
  README.md
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, type:fix, scope:cicd

#330 📝 🎨 ✨ (CICD): Enhanced the main README
  README.md
  src/README.md
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, type:documentation, scope:github-repo, scope:cicd

#331 🔥 (CICD): Removed <br> in main README
  README.md
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, scope:cicd
