Repository COS301-SE-2022/Twitter-Summariser, pull requests merged in 2022-08, with the labels that each got.

#560 🚚 (UI): Changed the manifest and icon of TS
  client/public/manifest.json
  client/public/maskable_icon.png
  client/public/maskable_icon_x128.png
  client/public/maskable_icon_x192.png
  client/public/maskable_icon_x384.png
  client/public/maskable_icon_x48.png
  client/public/maskable_icon_x512.png
  client/public/maskable_icon_x72.png
  client/public/maskable_icon_x96.png
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#561 🧱 ✨ (CICD): Added infra for ai module
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  client/src/resources/links.json
  package.json
  serverless.ts
  src/functions/__tests__/inte/back-end.int.ts
  src/functions/resources/APIresponse.ts
  text-summarisation/.gitignore
  text-summarisation/handler.py
  text-summarisation/serverless.ts
  yarn.lock
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:github-repo

#562 🚑 🔥 🐛 (CICD/API): Fixed bug with offline authorisers + Changed resource names
  .github/workflows/deploy.yml
  client/src/resources/links.json
  src/functions/authorizers/handler.ts
  src/functions/creator/handler.ts
  src/functions/resources/APIresponse.ts
Labels: priority:high, status:ready, role:dev-op, type:bug, type:fix, scope:backend

#563 ✨ (CICD): Made new job to deploy AI endpoint
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, scope:github-repo, scope:cicd

#564 🔥 💚 (CICD): Attempt to fix failing deployment
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:github-repo, scope:cicd

#565 🔥 💚 (CICD): Removed failing test
  .github/workflows/deploy.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#567 Testing if pipeline works
  .github/workflows/build.yml
Labels: priority:high, status:ready, role:dev-op, type:change, type:test, scope:github-repo, scope:cicd

#568 Testing to see if pipeline works
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, type:test, scope:cicd

#569 ➕ 🚑 💚 (CICD): Attempt to fix failing deployment
  Text-Summarisation/.gitignore
  package.json
  yarn.lock
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, type:test, scope:github-repo, scope:cicd

#570 💚 ✨ 🔥 (CICD): Major changes
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  Text-Summarisation/serverless.ts
  Twitter-Summariser/client/src/resources/links.json
  Twitter-Summariser/src/functions/resources/APIresponse.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:documentation, type:fix, scope:cicd

#571 🚚 (CICD): Added and modified README
  README.md
Labels: priority:high, status:ready, role:dev-op, type:change, type:documentation, scope:github-repo, scope:cicd

#573 🔥 (API): Removed unused var + 🐛 🚑 👽️ (API): Fixed refresh token bug
  Twitter-Summariser/src/functions/creator/handler.ts
Labels: priority:high, status:ready, type:change, role:backend-engineer, scope:backend

#574 ✨ (CICD): Code to run mulitple serverless offline
  .github/workflows/coverage.yml
  Text-Summarisation/serverless.ts
  Twitter-Summariser/serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:github-repo, scope:cicd

#575 🚑 (CICD): Attempt to fix failing coverage build
  .github/workflows/build.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:bug, type:fix, scope:github-repo, scope:cicd

#576 ✅ Add unit tests for report service
  Twitter-Summariser/src/__mocks__/aws-sdk.ts
  Twitter-Summariser/src/services/__tests__/report.service.spec.ts
  Twitter-Summariser/src/services/report.service.ts
Labels: priority:high, status:ready, role:team-lead, type:test, scope:backend, role:tester

#577 💄(UI): Profile UI implementation (40% done)
  Twitter-Summariser/client/public/assets/profile.png
  Twitter-Summariser/client/src/components/Profile.tsx
  Twitter-Summariser/client/src/components/styles/Profile.css
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#589 🚚 (CICD): Renamed resources
  .github/workflows/deploy.yml
  app/client/src/resources/links.json
  app/src/functions/resources/APIresponse.ts
  serverless-compose.ts
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#590 ✨ (CICD/API): Added file-type dependency + the image uploader endpoint
  app/package.json
  app/serverless.ts
  app/src/functions/profileImage/handler.ts
  app/src/functions/profileImage/index.ts
  app/yarn.lock
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, scope:backend, scope:cicd

#593 🔧✨ ✅ (UI/TESTING): Added Cypress Dependency and configurations for E2E testing
  .github/workflows/deploy.yml
  app/client/cypress.config.ts
  app/client/cypress/e2e/auth-e2e.cy.ts
  app/client/cypress/fixtures/example.json
  app/client/cypress/support/commands.ts
  app/client/cypress/support/e2e.ts
  app/client/package.json
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:test, role:tester

#594 🐛🔧 Updated links and Updated deploy distribution ID
  .github/workflows/deploy.yml
  app/client/src/resources/links.json
  app/src/functions/resources/APIresponse.ts
Labels: priority:medium, status:ready, role:frontend-engineer, type:enhance, type:fix, scope:backend

#595 👽️ 🔥 (CICD): Changing of stack
  .github/workflows/deploy.yml
  app/client/src/components/Home.tsx
  app/package.json
  app/src/functions/profileImage/handler.ts
  app/yarn.lock
Labels: priority:high, status:ready, role:dev-op, type:change, scope:github-repo, scope:cicd

#596 🚚 (CICD): Renamed resources
  .github/workflows/deploy.yml
  app/client/src/resources/links.json
  app/src/functions/resources/APIresponse.ts
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#597 🐛 🚑 (API): Fixed generate report issue
  app/client/yarn.lock
  app/serverless.ts
  app/src/functions/tweet/handler.ts
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, role:backend-engineer, scope:backend, scope:cicd

#598 ⚡ ✨ Added attempt 1 at fix for report search
  app/src/model/report/report.model.ts
  app/src/services/report.service.ts
Labels: priority:high, status:ready, type:bug, role:backend-engineer, scope:backend

#599 🐛 (UI/FIX): Fixed unpublish button bug and added permissions to shared reports
  app/client/src/components/GetPublishedReport.tsx
  app/client/src/components/SharedCard.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:fix

#600 💄(UI): Add custom tweet component added
  app/client/src/components/GenReport.tsx
  app/client/src/components/Modal.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#601 🔥 ✨ (AI/CICD): Major changes to the AI module
  app/package.json
  lib/.gitignore
  lib/handler.py
  lib/requirements.txt
  lib/serverless.ts
  package.json
  yarn.lock
Labels: priority:high, status:ready, scope:ai, role:dev-op, type:enhance, type:change, role:backend-engineer, scope:backend

#602 🚑 🔥 (CICD/AI): Attempt to fix failing deployment
  lib/serverless.ts
Labels: priority:high, status:ready, type:change, type:fix, role:backend-engineer, scope:backend

#603 🚑 🔥 (CICD/AI): Attempt to fix failing deployment
  lib/serverless.ts
Labels: priority:high, status:needs-tests, type:change, type:fix, role:backend-engineer, scope:backend

#604 🚑 (CICD): Attempt to fix failing deployment
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#605 🚑 (AI): Attempt to fix failing deployment
  lib/serverless.ts
Labels: priority:high, status:needs-tests, type:fix, role:backend-engineer, scope:backend

#606 🚑 (AI): Attempt to fix failing deployment
  .github/workflows/deploy.yml
  lib/serverless.ts
Labels: priority:high, status:needs-tests, scope:ai, type:fix, role:backend-engineer, scope:backend

#607 🚑 (AI): Attempt to fix failing deployment
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, scope:ai, type:fix, role:backend-engineer, scope:backend

#608 🚑 (AI): Attempt to fix failing deployment
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, scope:ai, type:fix, role:backend-engineer

#609 🚑 (AI): Attempt to fix failing deployment
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#610 🚑 (CICD/AI): Attempt to fix failing deployment
  .github/workflows/deploy.yml
  lib/serverless.ts
Labels: priority:high, status:needs-tests, scope:ai, role:dev-op, type:fix, role:backend-engineer, scope:cicd

#612 Dev/ishe
  .github/workflows/deploy.yml
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#613 Final attempt to fix deployment
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#611 ⚰️ ⚡ ✨ Added code to redefine add custom tweets and removed dead code
  app/src/functions/tweet/handler.ts
  app/src/services/report.service.ts
Labels: priority:high, status:ready, type:enhance, type:fix, role:backend-engineer, scope:backend

#614 Testing
  lib/serverless.ts
Labels: priority:high, status:needs-tests, scope:ai, role:dev-op, type:fix, scope:cicd

#615 Dev/ishe
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#616 Testing
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#617 Testing
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#618 Fix
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#619 Fix
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#620 Test
  .github/workflows/deploy.yml
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#621 Fix
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#622 Test
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#623 Test
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#624 Testing
  .github/workflows/deploy.yml
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#625 Test
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#626 Test
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#627 Test
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#628 🚑 (CICD): Attempt to fix deployment issue
  .github/workflows/deploy.yml
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#629 ✨🚀 (AI/CICD): Added tweepy dependency & test to see if deploy of module is a success
  lib/handler.py
  lib/requirements.txt
Labels: priority:high, status:needs-tests, scope:ai, role:dev-op, type:change, type:fix, role:backend-engineer, scope:cicd

#630 (API/SERV)🐛 ⚰️ ⚡ ✨ Fix for Jonah and My stuff
  app/serverless.ts
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/Functions/report.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/schedulers/index.ts
  app/src/services/report.service.ts
Labels: priority:high, status:ready, type:enhance, type:bug, role:backend-engineer, scope:backend

#631 💚 (CICD): Test to see why deploy fails
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:test, scope:cicd

#632 🐛 Deployment fix and custom tweets fixe
  app/src/functions/schedulers/index.ts
  app/src/functions/tweet/handler.ts
Labels: priority:high, status:ready, type:enhance, type:fix, role:backend-engineer, scope:backend

#633 🐛 ✨ (UI): Temporary fix to add permissions to viewing draft reports
  app/client/src/components/GenReport.tsx
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:change, type:fix

#634 ✨ (UI): Added code to add custom tweets from frontend
  app/client/src/components/Modal.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#635 ✅ (UI/TEST): Added a couple of basic E2E tests for signup and the splash page
  app/client/cypress/e2e/auth-e2e.cy.ts
  app/client/cypress/e2e/landing-e2e.cy.ts
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:test, role:tester

#636 ✨ (ai): AI module prototype endpoint complete
  lib/.gitignore
  lib/handler.py
  lib/requirements.txt
Labels: priority:high, status:needs-tests, scope:ai, type:enhance, type:change, type:test, role:backend-engineer

#637 ⚰️ 🔥 removed failing code.
  app/src/functions/schedulers/handler.ts
  app/src/functions/tweet/handler.ts
  app/src/model/schedule/schedule.model.ts
Labels: priority:high, status:ready, type:change, role:backend-engineer, scope:backend

#638 🐛 (UI): Final bug fix for adding custom tweets from frontend and backend
  app/client/src/components/GenReport.tsx
  app/src/functions/tweet/handler.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:fix

#639 ✨ (UI): Added code to delete tweets in draft reports
  app/client/src/components/GenReport.tsx
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#640 🗑️ ♻️ (UI): CODE CLEANUP - Adding relevant descriptions and comments to Index and App component files
  app/client/src/App.tsx
  app/client/src/index.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:documentation

#641 🔥 (ai): Fix for failing deployment
  app/yarn.lock
  lib/handler.py
  lib/requirements.txt
  lib/serverless.ts
Labels: priority:high, status:needs-tests, scope:ai, role:dev-op, type:fix, role:backend-engineer, scope:cicd

#642 ✨ (UI): Added code to query API to schedule report with temporary components
  app/client/package.json
  app/client/src/components/Home.tsx
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#643 🧪 ⚡ ✨ Trying a new verison with scheduler
  app/src/functions/schedulers/handler.ts
  app/src/functions/schedulers/index.ts
Labels: priority:high, status:needs-tests, type:enhance, type:bug, type:fix, role:backend-engineer, scope:backend

#644 (SERV/API):bug: fix for deployment
  app/src/functions/schedulers/index.ts
Labels: priority:high, status:needs-tests, type:enhance, type:bug, type:fix, role:backend-engineer, scope:backend

#645 (SERV/API) 🐛 fix for name bug
  app/src/functions/schedulers/index.ts
Labels: priority:high, status:needs-tests, type:enhance, type:bug, type:fix, role:backend-engineer, scope:backend

#646 ⚡ ✨ (SERV/API) Added function permissions
  app/serverless.ts
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, type:bug, role:backend-engineer, scope:backend

#647 🗃️ Add attribute to schedule report
  app/client/package.json
  app/client/src/service-worker.ts
  app/client/yarn.lock
  app/serverless.ts
  app/src/model/schedule/schedule.model.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#648 🔧 Change provider sid
  app/serverless.ts
Labels: priority:high, status:needs-tests, role:team-lead, type:fix, role:backend-engineer, scope:backend

#649 🔥 ✨ (cicd/ai): Major changes to the AI module
  lib/.dockerignore
  lib/.gitignore
  lib/dockerfile
  lib/get_model.py
  lib/handler.py
  lib/model/.gitkeep
  lib/requirements.txt
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, role:backend-engineer, scope:backend, scope:cicd

#650 ✨ 🚑 🔥 (ai/cicd): Finalized the AI module & fixed bugs + Created iam role for event bridge
  app/serverless.ts
  lib/handler.py
  lib/serverless.ts
Labels: priority:high, status:needs-tests, role:dev-op, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend, scope:cicd

#651 💄(UI): Advance search property and image upload feature for profile added and 80% ready.
  app/client/public/index.html
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/styles/Profile.css
Labels: priority:high, priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#652 ✨ ⚡ (SERV/API)added lambda permissions
  app/serverless.ts
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, type:change, type:bug, role:backend-engineer, scope:backend

#654 🐛 (API/SERV) Fix for getReport and more permissions for eventBridge
  app/serverless.ts
  app/src/functions/schedulers/handler.ts
  app/src/services/report.service.ts
Labels: priority:low, status:needs-tests, type:fix, role:backend-engineer, scope:backend

#653 🔥 📝 (cicd): minor changes
  README.md
  app/README.md
  lib/serverless.ts
  package.json
  yarn.lock
Labels: priority:high, status:ready, role:dev-op, type:change, type:documentation, role:backend-engineer, scope:backend, scope:cicd

#655 💄(UI): Image upload function created
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/Profile.tsx
Labels: priority:high, priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#656 ♻️ 👽️ 💄 (ui): removed log statements + connected profile upload to endpoint
  app/client/src/components/Profile.tsx
  app/client/yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:change

#657 (API/SERV)⚡ ✨ 🚚 Restrutured code and added writing to the datbase
  app/serverless.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/schedulers/index.ts
  app/src/model/schedule/schedule.model.ts
Labels: priority:high, status:not-ready, type:change, type:fix, role:backend-engineer, scope:backend

#658 💄(UI): Added the schedule report UI to the advanced search
  app/client/package.json
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/Home.tsx
  app/client/yarn.lock
Labels: priority:high, priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#659 (API/SERV)⚰️ removing authorizer for testing purposes
  app/src/functions/schedulers/index.ts
Labels: priority:high, status:needs-tests, type:change, type:bug, role:backend-engineer, scope:backend

#660 ⚡ ✨ 👽 (SERV/API) Finilsing report scheuler
  app/src/functions/schedulers/handler.ts
  app/src/functions/schedulers/index.ts
Labels: priority:high, status:needs-tests, type:enhance, type:fix, role:backend-engineer, scope:backend

#662 ⚡ 🐛 (API/SERV) Fix for gen report and removing autherizer
  app/src/functions/schedulers/index.ts
  app/src/services/report.service.ts
Labels: priority:high, status:needs-tests, type:enhance, type:fix, role:backend-engineer, scope:backend

#661 🚚 (UI): Renamed and updated draft and published report components for new routing
  app/client/src/App.tsx
  app/client/src/components/CLReports.tsx
  app/client/src/components/DraftCard.tsx
  app/client/src/components/DraftReport.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/SharedCard.tsx
  app/client/src/components/ViewHistory.tsx
  app/src/functions/schedulers/handler.ts
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:change

#663 🐛 ⚡️(API/SERV): Fixed draft report text block bug
  app/src/services/report.service.ts
Labels: priority:medium, status:ready, role:frontend-engineer, type:fix, role:backend-engineer, scope:backend

#664 ⚡️✨(UI): Updated routing to draft and published report pages to include report IDs in the URL
  app/client/src/App.tsx
  app/client/src/components/DraftCard.tsx
  app/client/src/components/DraftReport.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/ViewHistory.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#665 ✨ 💄 (UI): Minor changes
  app/client/src/pages/Login.tsx
  app/client/src/pages/Signup.tsx
  app/src/functions/profileImage/handler.ts
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:change, type:fix

#667 🐛 (UI): Fixed edit block bug and removed use of local storage to determine current report
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/DraftReport.tsx
  app/client/src/components/Modal.tsx
  app/client/src/components/SharedCard.tsx
  app/client/src/components/Text.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:fix
