Repository COS301-SE-2022/Twitter-Summariser, pull requests merged in 2022-09, with the labels that each got.

#668 🧱 ✨ (CICD): Added perms to put images in bucket
  app/serverless.ts
Labels: priority:medium, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#669 👽️ 🔥 ♻️ (UI/API): Major changes
  app/client/.eslintrc.json
  app/client/src/auth/RequiredAuth.tsx
  app/client/src/hooks/useRefreshToken.tsx
  app/client/src/pages/Login.tsx
  app/src/functions/authorizers/handler.ts
  app/src/functions/creator/handler.ts
Labels: priority:high, status:ready, type:enhance, type:change, role:backend-engineer, scope:backend

#670 💄 ✨ (UI): Added ScaleLoader for refresh page
  app/client/package.json
  app/client/src/components/PersistLogin.tsx
  app/client/src/pages/Login.tsx
  app/client/yarn.lock
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#671 💄 📱 (UI): Major changes to responsiveness of UI
  app/client/src/components/DraftCard.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/Profile.tsx
  app/client/src/hooks/useRefreshToken.tsx
  app/client/src/pages/Login.tsx
  app/src/functions/creator/handler.ts
  app/src/functions/profileImage/handler.ts
  app/src/model/creator/creator.model.ts
  app/src/services/__tests__/creator.service.spec.ts
  app/src/services/creator.service.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#672 ⚡️✨(UI): Moved all draft report functionality to single report component
  app/client/src/App.tsx
  app/client/src/components/DraftCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/SharedCard.tsx
  app/client/src/components/ViewHistory.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#673 📱 💄 ✨ (UI): Major changes (responsiveness) to the UI
  app/client/src/components/DraftCard.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/History.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/Reports.tsx
  app/client/src/pages/Login.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#674 ♻️📱 💄 (UI): Worked on the Shared Report Card + Linted all files
  app/client/src/App.tsx
  app/client/src/__tests__/components/Home.test.tsx
  app/client/src/__tests__/pages/Login.test.tsx
  app/client/src/__tests__/pages/Signup.test.tsx
  app/client/src/components/Button.tsx
  app/client/src/components/DraftCard.tsx
  app/client/src/components/DraftReport.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/History.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Modal.tsx
  app/client/src/components/PersistLogin.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/Shared.tsx
  app/client/src/components/SharedCard.tsx
  app/client/src/hooks/useRefreshToken.tsx
  app/client/src/pages/Login.tsx
  app/client/src/pages/Signup.tsx
  app/client/src/resources/links.json
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#675 🐛 (UI): Fixed shared permissions bug
  app/client/src/components/Report.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:bug

#676 📱 💄 ✨ (UI/API): Major changes to the UI
  app/client/src/App.tsx
  app/client/src/api/ConfigAxios.ts
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/Navigation.tsx
  app/client/src/components/TextSummariser.tsx
  app/client/src/pages/Landing.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#677 📱 💄 ✨ (UI): Fixed padding of loaders
  app/client/src/api/ConfigAxios.ts
  app/client/src/components/Drafts.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/History.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/Shared.tsx
  app/client/src/components/TextSummariser.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#679 :fire: 🔒 Sort and return result sets and reports in descending order
  app/client/package.json
  app/client/src/service-worker.ts
  app/client/yarn.lock
  app/src/functions/report/handler.ts
  app/src/functions/resultSet/handler.ts
  app/src/functions/tweet/handler.ts
Labels: priority:medium, status:ready, role:team-lead, type:enhance, type:change, role:backend-engineer, scope:backend

#678 ⚡ ✨ (API/SERV) Finished delete schedual report
  app/src/functions/report/index.ts
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, type:fix, role:backend-engineer, scope:backend

#680 ⚡ ✨ (API/SERV) Added key to reports
  app/src/functions/report/handler.ts
  app/src/model/report/report.model.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#681 👽️ 🚑 💄 (UI/API): Made fixes to backend & frontend
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/SharedCard.tsx
  app/client/yarn.lock
  app/src/functions/report/handler.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#682 💄 🔥 ✨ (UI): Fixed localStorage routing + Finished Entity Extraction & Sentiment Analysis
  app/client/src/components/MobileNavigation.tsx
  app/client/src/pages/Landing.tsx
  app/serverless.ts
  app/src/functions/sentimentAnalysis/handler.ts
  app/src/functions/sentimentAnalysis/index.ts
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:change, type:fix

#683 🔥 ✨ (CICD): Added analyse in Serverless.ts file
  app/serverless.ts
  app/src/functions/sentimentAnalysis/index.ts
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#684 ✨ (UI): Added code to query API to schedule report from frontend
  app/client/package.json
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/SharedCard.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#685 ⚡ ✨ (SERV/API) Wrapping up schedual report
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#686 💄 (UI): Image rendering on Profile page
  app/client/package.json
  app/client/src/components/Navigation.tsx
  app/client/src/components/Profile.tsx
  app/client/yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#687 ♻️ 💄 🔥 (UI): Major changes to profile components
  app/client/src/components/Drafts.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/SharedCard.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#688 🐛 (UI): Fixed delete report bug from card components
  app/client/src/components/DraftCard.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/ReportCard.tsx
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:bug, type:fix

#689 🔥 ♻️(UI): Removed log statements
  app/client/src/components/DraftCard.tsx
  app/client/src/components/DraftReport.tsx
  app/client/src/components/Drafts.tsx
  app/src/services/report.service.ts
Labels: priority:low, status:ready, scope:frontend, role:frontend-engineer, type:change

#690 🚧 💄(UI): Added some fixes and new UI style additions (!!! WORK IN PROGRESS !!!)
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Navigation.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/styles/Navigation.css
Labels: priority:high, status:not-ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#691 🐛 (API/SERV) Quick bug fix
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:ready, type:enhance, type:fix, role:backend-engineer, scope:backend

#692 ✨ Service worker caching
  app/client/package.json
  app/client/src/service-worker.ts
  app/client/yarn.lock
  app/src/functions/resultSet/handler.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:team-lead, type:enhance

#706 ✨ ⚡ (API/SERV) finished the ability to delete tweets
  app/src/functions/report/handler.ts
  app/src/functions/reportBlock/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/tweet/handler.ts
  app/src/model/tweet/tweet.model.ts
  app/src/services/tweet.service.ts
Labels: priority:high, status:needs-tests, type:fix, role:backend-engineer, scope:backend

#707 🚀 🚚(CICD): Renamed DistributionID
  .github/workflows/deploy.yml
  app/client/src/components/DraftCard.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/History.tsx
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/Shared.tsx
  app/client/src/components/SharedCard.tsx
  app/client/src/components/TextSummariser.tsx
  app/client/src/pages/Landing.tsx
  app/client/src/resources/links.json
  app/client/src/service-worker.ts
  app/src/functions/resources/APIresponse.ts
  lib/serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#708 ✨ 🚧 🔧 (DB) Add lambda function to create automated database table backups
  app/client/src/service-worker.ts
  app/serverless.ts
  app/src/functions/backup/handler.ts
  app/src/functions/backup/index.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#709 Add permission to lambda functions
  app/serverless.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#710 🔥 🔧 Remove unnecessary properties from lambda functions
  app/src/functions/backup/index.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:fix, role:backend-engineer, scope:backend

#711 🔥 Change ARN of lambda function
  app/src/functions/backup/index.ts
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:change, role:backend-engineer, scope:backend

#713 🔥🚚 🚀 (CICD): Renamed IDs for hosting + Stopped Model from being deployed
  .github/workflows/deploy.yml
  app/client/src/resources/links.json
  app/src/functions/resources/APIresponse.ts
  serverless-compose.ts
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#714 💄 🔥 ✨ (UI): Major changes to Text Summariser component
  app/client/package.json
  app/client/src/components/FileItem.tsx
  app/client/src/components/FileList.tsx
  app/client/src/components/FileUpload.tsx
  app/client/src/components/TextSummariser.tsx
  app/client/src/components/styles/FileItem.css
  app/client/yarn.lock
Labels: priority:high, status:not-ready, scope:frontend, role:frontend-engineer, type:enhance, type:change

#715 💄 🔥 ✨ (UI): Major changes to Text Summariser component
  app/client/cypress.config.ts
  app/client/cypress/e2e/auth-e2e.cy.ts
  app/client/cypress/e2e/landing-e2e.cy.ts
  app/client/cypress/fixtures/example.json
  app/client/cypress/support/commands.ts
  app/client/cypress/support/e2e.ts
  app/client/public/manifest.json
  app/client/src/components/FileItem.tsx
  app/client/src/components/FileList.tsx
  app/client/src/components/FileUpload.tsx
  app/client/src/components/TextSummariser.tsx
  app/client/src/components/styles/FileItem.css
  app/client/src/service-worker.ts
  app/package.json
  app/serverless.ts
  app/src/functions/backup/handler.ts
  app/src/functions/backup/index.ts
  app/src/functions/creator/handler.ts
  app/src/functions/profileImage/handler.ts
  app/src/functions/profileImage/index.ts
  app/src/functions/report/handler.ts
  app/src/functions/report/index.ts
  app/src/functions/reportBlock/handler.ts
  app/src/functions/resources/APIresponse.ts
  app/src/functions/resultSet/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/schedulers/index.ts
  app/src/functions/sentimentAnalysis/handler.ts
  app/src/functions/sentimentAnalysis/index.ts
  app/src/functions/tweet/handler.ts
  app/src/services/__tests__/permission.service.spec.ts
  app/src/services/__tests__/report.service.spec.ts
  app/src/services/creator.service.ts
  app/src/services/report.service.ts
  app/src/services/resultSet.service.ts
  app/src/services/tweet.service.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#716 ✨ 🗃️ 🔧 Add table for notifications
  app/serverless.ts
  app/src/model/notification/index.ts
  app/src/model/notification/notification.model.ts
  app/src/services/notification.service.ts
Labels: priority:medium, status:needs-tests, scope:db, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#717 🚀 🔥 ✨ (CICD/AI): Major changes to deployment of AI
  .gitignore
  app/client/src/api/ConfigAxios.ts
  app/client/src/components/FileUpload.tsx
  app/client/src/components/TextSummariser.tsx
  app/client/src/resources/links.json
  lib/text-extraction/handler.js
  lib/text-extraction/package.json
  lib/text-extraction/serverless.ts
  lib/text-extraction/yarn.lock
  lib/text-summariser/.dockerignore
  lib/text-summariser/.gitignore
  lib/text-summariser/dockerfile
  lib/text-summariser/get_model.py
  lib/text-summariser/handler.py
  lib/text-summariser/model/.gitkeep
  lib/text-summariser/requirements.txt
  lib/text-summariser/serverless.ts
  package.json
  serverless-compose.ts
  yarn.lock
Labels: priority:high, status:needs-tests, scope:ai, role:dev-op, type:enhance, type:change, scope:cicd

#718 🚀 💚 (CCID): Test to see if deployment is fixed
  app/client/src/App.tsx
Labels: priority:high, status:needs-tests, role:dev-op, type:fix, scope:cicd

#719 ⚡ ✨ (API/SERV) fix for some functions and testing of others
  app/src/functions/reportBlock/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/tweet/handler.ts
  app/src/services/tweet.service.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#720 🐛 (UI): Fixed schedule report bugs from frontend
  app/client/src/components/Home.tsx
  app/client/src/components/Navigation.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:fix

#722 💚 🚀 👷 (CICD): Deployment of text extract & summ
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, scope:ai, role:dev-op, type:change, type:fix, role:backend-engineer, scope:backend

#723 💄(UI): Navigation Implementation and Profile picture on mobile navigation
  app/client/package.json
  app/client/public/index.html
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/Navigation.tsx
  app/client/src/components/styles/MobileNavigation.css
  app/client/src/components/styles/Navigation.css
  app/client/yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#724 ✨ (UI): Updated schedule report to include repeat cycle
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Report.tsx
  app/client/yarn.lock
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#725 ✨ 💄 🎨 ➕ 🚧 Add notifications component
  app/client/package.json
  app/client/src/App.tsx
  app/client/src/components/NotificationCard.tsx
  app/client/src/components/Notifications.tsx
  app/client/src/pages/Landing.tsx
  app/client/yarn.lock
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, role:team-lead, type:enhance

#726 ✨ 🔧 🚧 (API) Add API endpoint to retrieve and delete notifications
  app/serverless.ts
  app/src/functions/notifications/handler.ts
  app/src/functions/notifications/index.ts
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/services/index.ts
Labels: priority:medium, status:ready, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#727 ✏️ Fix getReportBlock function
  app/src/services/__tests__/reportBlock.service.spec.ts
  app/src/services/reportBlock.service.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:fix, role:backend-engineer, scope:backend

#728 ✨ (UI): Added code to delete tweet from a draft report + code to show sentiment analysis in reports
  app/client/package.json
  app/client/src/components/Home.tsx
  app/client/src/components/Report.tsx
  app/client/yarn.lock
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#729 🔥 ✨ 💄 (CICD/UI/API): Major changes to text summarisation
  app/client/src/App.tsx
  app/client/src/api/ConfigAxios.ts
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/FileUpload.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/NotificationCard.tsx
  app/client/src/components/Notifications.tsx
  app/client/src/components/TextSummariser.tsx
  app/client/src/components/styles/Profile.css
  app/client/src/pages/Landing.tsx
  app/client/yarn.lock
  lib/text-summariser/handler.py
  lib/text-summariser/requirements.txt
  lib/text-summariser/serverless.ts
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend, scope:cicd

#730 🚑 🔥(UI): Fixed body of request
  app/client/src/components/TextSummariser.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:change, type:fix

#731 👽️ 🔥 (UI): Attempt to fix cors issue
  app/client/src/api/ConfigAxios.ts
  app/client/src/components/TextSummariser.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:change, type:fix

#732 💄👔 🔥 (UI): Finished generate summary, changed error response and accepted file types
  app/client/src/components/FileUpload.tsx
  app/client/src/components/TextSummariser.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#733 (API/SERV)🐛 Fixing custom tweets and delete tweet
  app/src/functions/reportBlock/handler.ts
  app/src/functions/tweet/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#734 (API/SERV)🐛 Fixing structure of report after deleting tweet
  app/src/functions/reportBlock/handler.ts
Labels: priority:high, status:needs-tests, type:fix, role:backend-engineer, scope:backend

#735 👔 💄 ✅ (UI): Finished logic to extract docx file
  app/client/package.json
  app/client/src/components/FileUpload.tsx
  app/client/yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#736 (API/SERV)⚡ ✨ Finished custom tweets and delete tweet for textbox
  app/src/functions/reportBlock/handler.ts
  app/src/functions/tweet/handler.ts
Labels: priority:high, status:ready, role:frontend-engineer, type:enhance, role:backend-engineer, scope:backend

#737 👔 💄 ✨ (UI): Finished text component of text summariser
  app/client/package.json
  app/client/src/components/FileUpload.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/TextSummariser.tsx
  app/client/yarn.lock
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix

#738 ✨ (UI): Added code to show trending tweets on home page using mock data
  app/client/src/components/Home.tsx
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#740 💄(UI): Major UI improvements
  app/client/package.json
  app/client/public/index.html
  app/client/src/components/DraftCard.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/History.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/Shared.tsx
  app/client/src/components/SharedCard.tsx
  app/client/src/pages/Login.tsx
  app/client/yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#739 ✨ (UI): Added code to show user permissions in report
  app/client/src/components/Report.tsx
  package.json
  yarn.lock
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#741 ✨ 🔥 🎨 💄 (UI): Integrate notification component with API queries
  app/client/src/components/NotificationCard.tsx
  app/client/src/components/Notifications.tsx
  app/src/functions/notifications/handler.ts
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/model/notification/notification.model.ts
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, role:team-lead, type:enhance, role:backend-engineer, scope:backend

#742 💄 ✨ 📱 (UI): Major adjustments to Text Summarisation component
  app/client/src/components/FileItem.tsx
  app/client/src/components/FileUpload.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/TextSummariser.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#743 (API/SERV) ⚡ ✨ Adding text to the first text block
  app/src/functions/report/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#744 (API/SERV)🐛 swapping map function for a loop
  app/src/functions/report/handler.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#746 💄(UI): Design for Mobile Navigation
  app/client/src/App.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/History.tsx
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/Navigation.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/Shared.tsx
  app/client/src/components/Something.tsx
  app/client/src/pages/Landing.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#745 (API/SERV)⚡ ✨ Added code and endpoint to get trending topics
  app/serverless.ts
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/trending/handler.ts
  app/src/functions/trending/index.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#747 ✨ 👽️ (API/LIB): Minor changes to text extraction
  app/client/src/resources/links.json
  lib/text-extraction/handler.js
  lib/text-extraction/package.json
  lib/text-extraction/serverless.ts
  lib/text-extraction/yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, role:backend-engineer, scope:backend

#748 🐛 (UI/API/SERV): Minor bug fixes to fix issues viewing a report
  app/client/src/App.tsx
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/Navigation.tsx
  app/client/src/components/Text.tsx
  app/client/src/pages/Landing.tsx
  app/src/functions/report/handler.ts
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:fix, scope:backend

#749 (API/SERV)🐛 Added code to add a style to the summarized text
  app/src/functions/report/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#751 ✨ (UI): Updated navigation after cloning/deleting + updated show semantic analysis icon
  app/client/src/components/Report.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#752 (API/SERV)🐛 Finished summarizing tweets
  app/src/functions/report/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#753 ✨ (UI): Added code to update the title in a report
  app/client/src/components/Report.tsx
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#754 (API/SERV)⚡ ✨ Added code and end point to edit the report title
  app/serverless.ts
  app/src/functions/report/handler.ts
  app/src/functions/report/index.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#755 ✨ (UI): Added code to query API to edit title in a draft report
  app/client/src/components/Report.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#756 (API/SERV)🔒 ⚡ ✨ added secuirty check for editing
  app/src/functions/report/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#757 💄 📱 🔥 (UI): Add mobile component for notifications
  app/client/src/components/MobileNotifications.tsx
  app/client/src/components/NotificationCard.tsx
  app/client/src/components/Notifications.tsx
  app/client/src/context/NotificationsContext.tsx
  app/client/src/pages/Landing.tsx
  app/src/functions/notifications/handler.ts
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, role:team-lead, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#758 💄 (UI): Some UI touches
  app/client/src/components/DraftCard.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/History.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/Navigation.tsx
  app/client/src/components/NotificationCard.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/SharedCard.tsx
  app/client/src/components/Something.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:bug, type:fix, role:designer

#759 💄 ✨ (UI): Updated genReport handler + 👽️ 🔥 ✨ (API): Integrated textSumm with genReport
  app/client/src/components/Home.tsx
  app/serverless.ts
  app/src/functions/report/handler.ts
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#761 💄 (UI): UI related bug fixes
  app/client/src/components/DraftCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/SharedCard.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:fix, role:designer

#763 ✨ (CICD): Imported lib
  app/serverless.ts
Labels: priority:high, status:ready, role:frontend-engineer, type:change, role:backend-engineer, scope:backend

#764 (API/SERV)⚡ ✨ Switched post request to lambda invocation
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#765 💄 📱 🔥 ♻️ 🐛 (UI): Fix delete notifications bug + Fix alignment of components
  app/client/src/components/MobileNotifications.tsx
  app/client/src/components/NotificationCard.tsx
  app/client/src/components/Notifications.tsx
  app/client/src/context/NotificationsContext.tsx
  app/client/src/pages/Landing.tsx
  app/src/functions/notifications/handler.ts
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/handler.ts
Labels: priority:medium, status:ready, scope:frontend, role:frontend-engineer, role:team-lead, type:bug, type:fix

#766 🔥 💄 ✨ (UI): Made changes to the UI
  app/client/src/components/Button.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/History.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/MobileNotifications.tsx
  app/client/src/components/NotificationCard.tsx
  app/client/src/components/Notifications.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/PublishedText.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/Shared.tsx
  app/client/src/components/Text.tsx
  app/client/src/components/TextSummariser.tsx
  app/client/src/components/ViewHistory.tsx
  app/client/src/components/scroll/ScrollToTop.tsx
  app/client/src/context/NotificationsContext.tsx
  app/client/src/pages/Landing.tsx
  app/client/src/pages/Login.tsx
  app/client/src/pages/Signup.tsx
  app/src/functions/report/handler.ts
  app/src/functions/report/index.ts
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#768 👽️ 🔥 (API): Fix genReport logic for prod & dev + 💄 ♻️ 🚑 (UI): Fixed genReport for local and prod
  app/client/cypress.config.ts
  app/client/cypress/e2e/performance.cy.ts
  app/client/src/components/Drafts.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/History.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/Shared.tsx
  app/client/src/components/Something.tsx
  app/client/src/components/ViewHistory.tsx
  app/serverless.ts
  app/src/functions/notifications/handler.ts
  app/src/functions/notifications/index.ts
  app/src/functions/report/handler.ts
  app/src/functions/reportBlock/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/trending/handler.ts
  app/src/functions/tweet/handler.ts
  app/src/functions/warmup/handler.ts
  app/src/functions/warmup/index.ts
  app/src/model/notification/index.ts
  app/src/model/notification/notification.model.ts
  app/src/services/notification.service.ts
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#769 📱 💄 🚑 (UI): Fixed responsivenes of Pub & Drafts
  app/client/src/components/DraftCard.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/Reports.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#770 👽️ 🔥 🚑 (API): Attempt to fix scheduleReport
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:needs-tests, type:change, type:fix, role:backend-engineer, scope:backend

#771 (API/SERV)🐛 🔥 Arttempted fix for schedual report and trending reports
  app/src/functions/schedulers/handler.ts
  app/src/functions/trending/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#772 (API/SERV)🐛 use of twitter cleint to peform trending tweets
  app/src/functions/trending/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#773 (API/SERV)➕ Adding dependency
  app/package.json
  app/yarn.lock
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#774 (API/SERV)⚡ ✨ 🔥 🚚 FInished trending tweets
  app/src/functions/trending/handler.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#775 (API/SERV)⚡ ✨ Added code to return the sentiment of tweets
  app/serverless.ts
  app/src/functions/trending/handler.ts
  app/src/functions/tweet/handler.ts
  app/src/functions/tweet/index.ts
Labels: priority:high, status:needs-tests, type:enhance, role:backend-engineer, scope:backend

#776 🔥 👽️ 🚑 (API): Fixed schedule report + ✨ 💄 (UI): Updates to Login & Signup
  app/client/src/pages/Login.tsx
  app/client/src/pages/Signup.tsx
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#777 🚸 (UI): Redirect user when report is generated + ✅ (TEST): Add unit test for service functions
  app/client/src/components/Home.tsx
  app/src/services/__tests__/notification.service.spec.ts
Labels: priority:medium, status:ready, scope:frontend, scope:db, role:team-lead, type:change, type:test, role:backend-engineer, scope:backend, role:tester

#778 (API/SERV)⚡ ✨ finished sentiment anlyssis
  app/src/functions/tweet/handler.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#779 (API)⚡ change from get to post for trending topics
  app/src/functions/trending/index.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#780 (TESTER)🧪 Readding integration tests
  app/src/functions/__tests__/inte/back-end.int.ts
Labels: priority:high, status:needs-tests, type:enhance, type:fix, scope:backend, role:tester

#781 🚀 🔥 🚚 (CICD): Re-deployment of all stacks
  .github/workflows/deploy.yml
  app/client/src/components/Button.tsx
  app/client/src/components/DraftCard.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/ViewHistory.tsx
  app/client/src/resources/links.json
  app/src/functions/schedulers/handler.ts
  lib/text-summariser/serverless.ts
Labels: priority:high, status:ready, scope:frontend, role:dev-op, type:enhance, type:change, role:backend-engineer, scope:backend, scope:cicd

#782 👽️ 🚑 (API): Fixed cors header response
  app/src/functions/resources/APIresponse.ts
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:backend

#783 💄 👽️ 🚚 (API): Changed distribution URL + Changed IDs of text summarisation
  app/client/src/api/ConfigAxios.ts
  lib/text-extraction/handler.js
  lib/text-summariser/handler.py
  lib/text-summariser/serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#784 ✨ 👽️ 🚑 (API): Fixed genReport error
  app/src/functions/report/handler.ts
Labels: priority:high, status:ready, type:change, type:fix, role:backend-engineer, scope:backend

#785 💄(UI): Major UI Improvements
  app/client/src/components/Home.tsx
  app/client/src/components/Modals.tsx
  app/client/src/components/Report.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:designer

#786 📱 💄 🔥 ✨ (UI): Major changes to UI
  app/client/src/components/DraftCard.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/Shared.tsx
  app/client/src/components/SharedCard.tsx
  app/src/functions/__tests__/inte/back-end.int.ts
  app/src/functions/report/handler.ts
  app/src/functions/trending/handler.ts
  app/src/functions/tweet/handler.ts
  app/src/functions/tweet/index.ts
  app/src/services/__tests__/notification.service.spec.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#787 💄 (UI): Major changes to the report component
  app/client/src/components/Report.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#788 🚀 (CICD): Attempt to fix deployment
  app/client/src/components/MobileNotifications.tsx
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#789 💄 (UI): Modal updated with add tweet shandis
  app/client/src/components/Modals.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/ReportCard.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#790 📱 💄 ✨ (UI): Fixed scroll & notifications buttons + Fixed margin of FileUpload
  app/client/src/components/FileUpload.tsx
  app/client/src/components/MobileNotifications.tsx
  app/client/src/components/scroll/ScrollToTop.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#791 ✅✨ (UI): Implemented sentiment analysis for home page and added unit tests for new login page components
  app/client/src/App.tsx
  app/client/src/__tests__/components/AuthLink.test.tsx
  app/client/src/__tests__/components/Button.test.tsx
  app/client/src/__tests__/components/Heading.test.tsx
  app/client/src/__tests__/components/Input.test.tsx
  app/client/src/__tests__/components/Logo.test.tsx
  app/client/src/components/AuthLink.tsx
  app/client/src/components/ButtonComponent.tsx
  app/client/src/components/Checkbox.tsx
  app/client/src/components/Heading.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Input.tsx
  app/client/src/components/LoginPage.tsx
  app/client/src/components/LogoComponent.tsx
  app/client/src/pages/TestPage.tsx
  app/client/tailwind.config.js
Labels: priority:high, status:ready, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance, type:test, role:tester

#792 📱 🔥 💄 (UI): Major improvements
  app/client/src/components/DraftReport.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/MobileNotifications.tsx
  app/client/src/components/ViewHistory.tsx
  app/client/src/pages/Landing.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#793 (API/SERV)⚡ ✨ Embedded sentiment into report
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/index.ts
  app/src/services/__tests__/report.service.spec.ts
  app/src/services/report.service.ts
Labels: priority:high, status:ready, type:enhance, role:backend-engineer, scope:backend

#794 ✨ 💄 ♻️ (UI): Enhanced the advanced search modal
  app/client/src/__tests__/components/AuthLink.test.tsx
  app/client/src/__tests__/components/Button.test.tsx
  app/client/src/__tests__/components/Heading.test.tsx
  app/client/src/__tests__/components/Input.test.tsx
  app/client/src/__tests__/components/Logo.test.tsx
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/AuthLink.tsx
  app/client/src/components/ButtonComponent.tsx
  app/client/src/components/Checkbox.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/Heading.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Input.tsx
  app/client/src/components/LoginPage.tsx
  app/client/src/components/LogoComponent.tsx
  app/client/src/components/Modals.tsx
  app/client/src/pages/TestPage.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#795 🔥 🐛 Remove code that failed get report
  app/client/src/components/MobileNotifications.tsx
  app/src/services/report.service.ts
Labels: priority:high, status:ready, role:team-lead, type:fix, role:backend-engineer, scope:backend

#797 👽️ 🔥 🚑 (API): Fixed genReport parameters bug + Major changes to UI
  app/client/src/components/Explore.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/MobileNotifications.tsx
  app/client/src/components/Modals.tsx
  app/client/src/components/ViewHistory.tsx
  app/src/functions/report/handler.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#798 ✨ (UI): Added code to query API to get trending topics
  app/client/src/components/Home.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#799 💄(UI): Modals fully integrated
  app/client/src/components/Modals.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/SharedCard.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#800 👽️ 🚑 🔥 (API): Fixed genReport parameter extract
  app/client/src/components/Home.tsx
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/index.ts
  app/src/services/report.service.ts
Labels: priority:high, status:ready, type:change, type:fix, role:backend-engineer, scope:backend

#803 🐛 (UI): Fixed re-order + edit title permission + missing clone report author bugs
  app/client/src/components/Report.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:fix

#801 (API/SERV)🚚 Moving report generation from service layer
  app/src/functions/report/handler.ts
  app/src/services/__tests__/report.service.spec.ts
  app/src/services/report.service.ts
Labels: priority:high, status:ready, type:enhance, type:fix, role:backend-engineer, scope:backend

#805 (API/SERV/AI)⚡ ✨ added seniment anlysis
  app/src/functions/report/handler.ts
Labels: priority:high, status:ready, scope:ai, type:enhance, type:fix, role:backend-engineer, scope:backend

#804 📱 🔥 💄 (UI): Major changes to UI
  app/client/src/App.tsx
  app/client/src/components/ButtonComponent.tsx
  app/client/src/components/DraftCard.tsx
  app/client/src/components/DraftReport.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/Explore.tsx
  app/client/src/components/Heading.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/LoginPage.tsx
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/MobileNotifications.tsx
  app/client/src/components/Modal.tsx
  app/client/src/components/Modals.tsx
  app/client/src/components/Navigation.tsx
  app/client/src/components/NotificationCard.tsx
  app/client/src/components/Notifications.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/PublishedText.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/Shared.tsx
  app/client/src/components/SharedCard.tsx
  app/client/src/components/Something.tsx
  app/client/src/components/Splash.tsx
  app/client/src/components/Text.tsx
  app/client/src/components/ViewHistory.tsx
  app/src/functions/report/handler.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, type:fix

#802 🐛 🔥 Bug fixes to notifications and custom tweets
  app/client/src/components/NotificationCard.tsx
  app/src/functions/notifications/handler.ts
  app/src/functions/report/handler.ts
  app/src/functions/reportBlock/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/tweet/handler.ts
  app/src/model/report/report.model.ts
  app/src/services/__tests__/report.service.spec.ts
  app/src/services/report.service.ts
Labels: priority:high, status:ready, status:needs-tests, scope:frontend, role:team-lead, type:bug, type:fix, role:backend-engineer, scope:backend

#806 🐛 Fix bug with get shared report
  app/src/functions/report/handler.ts
Labels: priority:high, status:ready, scope:db, role:team-lead, type:bug, role:backend-engineer, scope:backend

#807 ✨ (UI): Implemented sentiment analysis in a draft report
  app/client/src/components/Report.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance

#808 (API/SERV)🐛 fix for schedual report
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:ready, type:enhance, type:fix, role:backend-engineer, scope:backend

#809 🐛 🗃️ Stop dynamodb from overriding
  app/client/src/components/Notifications.tsx
  app/src/services/__tests__/report.service.spec.ts
  app/src/services/report.service.ts
Labels: priority:high, status:needs-tests, scope:db, role:team-lead, type:change, role:backend-engineer, scope:backend

#810 💄 🐛 (UI): Fix notification component
  app/client/src/components/Notifications.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:team-lead, type:fix

#811 Revert "(API/SERV)🐛 fix for schedual report"
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#812 Revert "🐛 🗃️ Stop dynamodb from overriding"
  app/src/services/__tests__/report.service.spec.ts
  app/src/services/report.service.ts
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#813 ✅♻️ 👽️ 🔥 (AI): Refactored some code in AI module + Added unit tests
  app/client/src/api/ConfigAxios.ts
  app/src/services/__tests__/creator.service.spec.ts
  app/src/services/__tests__/notification.service.spec.ts
  app/src/services/__tests__/permission.service.spec.ts
  app/src/services/__tests__/report.service.spec.ts
  lib/text-summariser/handler.py
  lib/text-summariser/requirements.txt
  lib/text-summariser/serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:enhance, type:change, role:backend-engineer, scope:backend

#814 ✨ ✅ (TEST): Added unit tests for frontend
  .github/workflows/deploy.yml
  app/client/src/App.tsx
  app/client/src/__tests__/components/Explore.test.tsx
  app/client/src/__tests__/components/Reports.test.tsx
  app/client/src/__tests__/components/TextSummariser.test.tsx
  app/client/src/api/ConfigAxios.ts
  app/client/src/components/TextSummariser.tsx
  app/client/src/resources/links.json
  app/client/src/service-worker.ts
  app/serverless.ts
  app/src/functions/report/handler.ts
  app/src/functions/resources/APIresponse.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/warmup/handler.ts
  lib/text-extraction/handler.js
  lib/text-extraction/serverless.ts
  lib/text-summariser/handler.py
  lib/text-summariser/serverless.ts
Labels: priority:high, status:ready, scope:frontend, type:test, role:tester

#815 🚀 ✨ (CICD): Changed deploy args
  .github/workflows/deploy.yml
Labels: priority:high, status:needs-tests, role:dev-op, type:change, type:fix, scope:cicd

#816 🚚 🚀 (CICD): Changed access origin & IDs
  .github/workflows/deploy.yml
  app/client/src/api/ConfigAxios.ts
  app/client/src/resources/links.json
  app/src/functions/resources/APIresponse.ts
  lib/text-extraction/handler.js
  lib/text-summariser/handler.py
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#817 🚀 🚑 (CICD): Attempt to fix deployment
  .github/workflows/deploy.yml
Labels: status:ready, role:dev-op, type:change, type:fix, scope:cicd

#818 🚀 🚚 (CICD): Changed IDs and Access Origins
  .github/workflows/deploy.yml
  app/client/src/api/ConfigAxios.ts
  app/client/src/components/Home.tsx
  app/client/src/components/ViewHistory.tsx
  app/client/src/resources/links.json
  app/src/functions/resources/APIresponse.ts
  lib/text-extraction/handler.js
  lib/text-summariser/handler.py
  lib/text-summariser/serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:change, type:fix, scope:cicd

#819 👽️ ✨ 🔥 (API): Fix for genReport for scheduling + New function URL for genReport
  app/client/src/components/ButtonComponent.tsx
  app/client/src/components/DraftReport.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/Modals.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/Text.tsx
  app/client/src/components/ViewHistory.tsx
  app/client/src/service-worker.ts
  app/src/functions/report/handler.ts
  app/src/functions/warmup/handler.ts
  app/src/services/report.service.ts
  app/src/services/reportBlock.service.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend, scope:cicd

#820 👽️ 💄 ✨ (UI/AI): Major changes to UI
  app/client/src/__tests__/components/Explore.test.tsx
  app/client/src/__tests__/components/Reports.test.tsx
  app/client/src/__tests__/components/TextSummariser.test.tsx
  app/client/src/components/AdvanceSearch.tsx
  app/client/src/components/Drafts.tsx
  app/client/src/components/ExploreCard.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/MobileNavigation.tsx
  app/client/src/components/NotificationCard.tsx
  app/client/src/components/Profile.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/Reports.tsx
  app/client/src/components/SharedCard.tsx
  app/src/functions/notifications/handler.ts
  app/src/functions/profileImage/handler.ts
  app/src/functions/report/handler.ts
  app/src/functions/reportBlock/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/tweet/handler.ts
  app/src/functions/warmup/handler.ts
  app/src/services/__tests__/creator.service.spec.ts
  app/src/services/__tests__/notification.service.spec.ts
  app/src/services/__tests__/permission.service.spec.ts
  app/src/services/__tests__/report.service.spec.ts
  lib/text-summariser/handler.py
  lib/text-summariser/requirements.txt
  lib/text-summariser/serverless.ts
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, role:dev-op, type:enhance, type:change, type:fix, role:backend-engineer, scope:backend

#821 ✅✨ (UI): Integrated new Menu component into report component + Added unit tests for home page
  app/client/src/__tests__/components/Home.test.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/MenuComponent.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/TweetComponent.tsx
  app/client/src/components/TweetResponse.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:test, role:tester

#822 ✨ (UI): Added code to scroll to top when trend is clicked + made tweet container rounded
  app/client/src/components/ButtonComponent.tsx
  app/client/src/components/Home.tsx
  app/client/src/components/TweetResponse.tsx
Labels: priority:medium, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#824 ✨ 🔥 👽️ (API): Attempt to fix scheduleReport
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/handler.ts
Labels: priority:high, status:needs-tests, type:fix, role:backend-engineer, scope:backend

#825 🚀 (CICD): Redploy
  app/src/functions/report/handler.ts
Labels: priority:high, status:ready, scope:db, role:dev-op, type:fix

#826 🚀 🚚 (CICD): Renamed deployment IDs + Re-deployed text-summariser
  .github/workflows/deploy.yml
  app/client/src/api/ConfigAxios.ts
  app/client/src/components/Home.tsx
  app/client/src/components/ViewHistory.tsx
  app/client/src/resources/links.json
  app/src/functions/report/handler.ts
  app/src/functions/resources/APIresponse.ts
  app/src/functions/schedulers/handler.ts
  lib/text-extraction/handler.js
  lib/text-summariser/handler.py
  lib/text-summariser/serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#823 💄(UI): Major UI Improvements
  app/client/src/components/DraftCard.tsx
  app/client/src/components/History.tsx
  app/client/src/components/HistoryCard.tsx
  app/client/src/components/MenuComponent.tsx
  app/client/src/components/Report.tsx
  app/client/src/components/ReportCard.tsx
  app/client/src/components/Text.tsx
  app/client/src/components/TweetResponse.tsx
  app/client/src/pages/Landing.tsx
  app/client/yarn.lock
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:enhance, type:change, role:designer

#827 ✨ (UI): Removed clone report from published report
  app/client/src/components/Report.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:enhance

#829 📝 Update ReadMe
  README.md
Labels: priority:high, status:ready, role:team-lead, type:documentation, scope:github-repo
