Repository COS301-SE-2022/Twitter-Summariser, pull requests merged in 2022-10, with the labels that each got.

#830 ✨ 🚀 (CICD): Re-deployment of the stack
  .github/workflows/deploy.yml
  app/client/src/resources/links.json
  app/serverless.ts
  app/src/functions/report/handler.ts
  app/src/functions/resources/APIresponse.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/summarise/handler.ts
  app/src/functions/summarise/index.ts
  lib/text-extraction/handler.js
  lib/text-summariser/handler.py
  lib/text-summariser/serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:change, scope:github-repo, scope:cicd

#831 🚀 🚑 (CICD): Fixed typo in dockerImage digest
  lib/text-summariser/serverless.ts
Labels: priority:high, status:ready, role:dev-op, type:change, scope:cicd

#832 💄 🔥 (UI): Testing new UI endpoint
  app/client/src/components/Home.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:change, type:fix

#833 🔥 (CICD): Removed unused import
  app/client/src/components/Home.tsx
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#834 🚑 (UI): Fixed typo
  app/client/src/components/TextSummariser.tsx
Labels: priority:high, status:ready, scope:frontend, role:frontend-engineer, type:change, type:fix

#837 💄 🚑 (UI): Fixed trim
  app/client/src/components/Text.tsx
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:fix

#838 💄 🚑 👽️ (UI/API): Fixed timeout issues + Fixed parameter handling
  app/client/src/components/Home.tsx
  app/client/src/components/Text.tsx
  app/client/src/components/ViewHistory.tsx
  app/src/functions/report/handler.ts
  app/src/functions/summarise/handler.ts
Labels: priority:high, status:needs-tests, scope:frontend, role:frontend-engineer, type:change, type:fix, role:backend-engineer, scope:backend

#839 ♻️ (CICD): Linted all files
  app/client/src/components/Home.tsx
  app/client/src/components/TextSummariser.tsx
  app/client/src/components/TweetComponent.tsx
  app/client/src/components/ViewHistory.tsx
  app/src/functions/report/handler.ts
  app/src/functions/schedulers/handler.ts
  app/src/functions/summarise/handler.ts
  app/src/functions/summarise/index.ts
  app/src/services/__tests__/report.service.spec.ts
Labels: priority:high, status:ready, role:dev-op, type:fix, scope:cicd

#840 📝 Update ReadMe
  README.md
Labels: priority:high, status:ready, role:team-lead, type:documentation, scope:github-repo

#841 ✨ 🔥 👽️ (API): Attempt to fix clone report
  app/src/functions/report/handler.ts
Labels: priority:high, status:needs-tests, type:change, type:fix, role:backend-engineer, scope:backend
